/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type ProvingStateStruct = {
  current_hash: BytesLike;
  expected_hash: BytesLike;
  current_index: BigNumberish;
  outputs: BytesLike[][];
  prepared_public_inputs: BytesLike[];
  prepared_proof: BytesLike;
  proof_verifier: AddressLike;
  commited_processor_public_key: BigNumberish[];
  initiator: AddressLike;
};

export type ProvingStateStructOutput = [
  current_hash: string,
  expected_hash: string,
  current_index: bigint,
  outputs: string[][],
  prepared_public_inputs: string[],
  prepared_proof: string,
  proof_verifier: string,
  commited_processor_public_key: bigint[],
  initiator: string
] & {
  current_hash: string;
  expected_hash: string;
  current_index: bigint;
  outputs: string[][];
  prepared_public_inputs: string[];
  prepared_proof: string;
  proof_verifier: string;
  commited_processor_public_key: bigint[];
  initiator: string;
};

export interface ChainedProofInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ACTION_CHAIN_PROOF_VERIFY"
      | "ACTION_PASS_SIGNAL"
      | "ACTION_PASS_SIGNAL_PLUSONE"
      | "ACTION_PREPARE_NEXT_PROOF"
      | "ACTION_START_UNSEALING"
      | "ACTION_STATIC_INPUT"
      | "ACTION_VALIDATE_DATA_ROOT"
      | "ACTION_VALIDATE_TIMESTAMP"
      | "dryrun_chain_pass_signal"
      | "dryrun_chain_proof_verify"
      | "dryrun_chain_static_input"
      | "dryrun_prepare_next_proof"
      | "dryrun_start_proving"
      | "dryrun_validate_data_root"
      | "dryrun_validate_timestamp"
      | "forced_opening_verifier"
      | "has_data_stream_root"
      | "provingStates"
      | "public_proof_verifier"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ACTION_CHAIN_PROOF_VERIFY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACTION_PASS_SIGNAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACTION_PASS_SIGNAL_PLUSONE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACTION_PREPARE_NEXT_PROOF",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACTION_START_UNSEALING",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACTION_STATIC_INPUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACTION_VALIDATE_DATA_ROOT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACTION_VALIDATE_TIMESTAMP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dryrun_chain_pass_signal",
    values: [ProvingStateStruct, BigNumberish[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "dryrun_chain_proof_verify",
    values: [ProvingStateStruct, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "dryrun_chain_static_input",
    values: [ProvingStateStruct, BytesLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "dryrun_prepare_next_proof",
    values: [ProvingStateStruct, AddressLike, BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dryrun_start_proving",
    values: [AddressLike, BytesLike[], BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "dryrun_validate_data_root",
    values: [
      ProvingStateStruct,
      AddressLike,
      BigNumberish,
      boolean,
      BytesLike,
      BytesLike[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "dryrun_validate_timestamp",
    values: [
      ProvingStateStruct,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "forced_opening_verifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "has_data_stream_root",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "provingStates",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "public_proof_verifier",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "ACTION_CHAIN_PROOF_VERIFY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ACTION_PASS_SIGNAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ACTION_PASS_SIGNAL_PLUSONE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ACTION_PREPARE_NEXT_PROOF",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ACTION_START_UNSEALING",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ACTION_STATIC_INPUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ACTION_VALIDATE_DATA_ROOT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ACTION_VALIDATE_TIMESTAMP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dryrun_chain_pass_signal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dryrun_chain_proof_verify",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dryrun_chain_static_input",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dryrun_prepare_next_proof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dryrun_start_proving",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dryrun_validate_data_root",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dryrun_validate_timestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forced_opening_verifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "has_data_stream_root",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "provingStates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "public_proof_verifier",
    data: BytesLike
  ): Result;
}

export interface ChainedProof extends BaseContract {
  connect(runner?: ContractRunner | null): ChainedProof;
  waitForDeployment(): Promise<this>;

  interface: ChainedProofInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ACTION_CHAIN_PROOF_VERIFY: TypedContractMethod<[], [string], "view">;

  ACTION_PASS_SIGNAL: TypedContractMethod<[], [string], "view">;

  ACTION_PASS_SIGNAL_PLUSONE: TypedContractMethod<[], [string], "view">;

  ACTION_PREPARE_NEXT_PROOF: TypedContractMethod<[], [string], "view">;

  ACTION_START_UNSEALING: TypedContractMethod<[], [string], "view">;

  ACTION_STATIC_INPUT: TypedContractMethod<[], [string], "view">;

  ACTION_VALIDATE_DATA_ROOT: TypedContractMethod<[], [string], "view">;

  ACTION_VALIDATE_TIMESTAMP: TypedContractMethod<[], [string], "view">;

  dryrun_chain_pass_signal: TypedContractMethod<
    [
      state: ProvingStateStruct,
      public_input_indexes: BigNumberish[],
      output_proof_indexes: BigNumberish[],
      output_indexes: BigNumberish[]
    ],
    [ProvingStateStructOutput],
    "view"
  >;

  dryrun_chain_proof_verify: TypedContractMethod<
    [state: ProvingStateStruct, ingore_proof: boolean],
    [ProvingStateStructOutput],
    "view"
  >;

  dryrun_chain_static_input: TypedContractMethod<
    [state: ProvingStateStruct, inputs: BytesLike[], indexes: BigNumberish[]],
    [ProvingStateStructOutput],
    "view"
  >;

  dryrun_prepare_next_proof: TypedContractMethod<
    [
      state: ProvingStateStruct,
      _verifier: AddressLike,
      _publicInputs: BytesLike[],
      _proof: BytesLike
    ],
    [ProvingStateStructOutput],
    "view"
  >;

  dryrun_start_proving: TypedContractMethod<
    [
      verifier: AddressLike,
      public_inputs: BytesLike[],
      proof: BytesLike,
      verify_proof: boolean
    ],
    [ProvingStateStructOutput],
    "view"
  >;

  dryrun_validate_data_root: TypedContractMethod<
    [
      state: ProvingStateStruct,
      datastream: AddressLike,
      public_input_index: BigNumberish,
      is_delayed_proof: boolean,
      optional_dual_tree_proof: BytesLike,
      optional_dual_tree_public_inputs: BytesLike[],
      merkle_root_index: BigNumberish
    ],
    [ProvingStateStructOutput],
    "view"
  >;

  dryrun_validate_timestamp: TypedContractMethod<
    [
      state: ProvingStateStruct,
      output_proof_index: BigNumberish,
      output_index: BigNumberish,
      public_input_index: BigNumberish,
      timestamp_window: BigNumberish
    ],
    [ProvingStateStructOutput],
    "view"
  >;

  forced_opening_verifier: TypedContractMethod<[], [string], "view">;

  has_data_stream_root: TypedContractMethod<
    [_datastream: AddressLike, _root: BytesLike],
    [boolean],
    "view"
  >;

  provingStates: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string, string, string] & {
        current_hash: string;
        expected_hash: string;
        current_index: bigint;
        prepared_proof: string;
        proof_verifier: string;
        initiator: string;
      }
    ],
    "view"
  >;

  public_proof_verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ACTION_CHAIN_PROOF_VERIFY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ACTION_PASS_SIGNAL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ACTION_PASS_SIGNAL_PLUSONE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ACTION_PREPARE_NEXT_PROOF"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ACTION_START_UNSEALING"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ACTION_STATIC_INPUT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ACTION_VALIDATE_DATA_ROOT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ACTION_VALIDATE_TIMESTAMP"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dryrun_chain_pass_signal"
  ): TypedContractMethod<
    [
      state: ProvingStateStruct,
      public_input_indexes: BigNumberish[],
      output_proof_indexes: BigNumberish[],
      output_indexes: BigNumberish[]
    ],
    [ProvingStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "dryrun_chain_proof_verify"
  ): TypedContractMethod<
    [state: ProvingStateStruct, ingore_proof: boolean],
    [ProvingStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "dryrun_chain_static_input"
  ): TypedContractMethod<
    [state: ProvingStateStruct, inputs: BytesLike[], indexes: BigNumberish[]],
    [ProvingStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "dryrun_prepare_next_proof"
  ): TypedContractMethod<
    [
      state: ProvingStateStruct,
      _verifier: AddressLike,
      _publicInputs: BytesLike[],
      _proof: BytesLike
    ],
    [ProvingStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "dryrun_start_proving"
  ): TypedContractMethod<
    [
      verifier: AddressLike,
      public_inputs: BytesLike[],
      proof: BytesLike,
      verify_proof: boolean
    ],
    [ProvingStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "dryrun_validate_data_root"
  ): TypedContractMethod<
    [
      state: ProvingStateStruct,
      datastream: AddressLike,
      public_input_index: BigNumberish,
      is_delayed_proof: boolean,
      optional_dual_tree_proof: BytesLike,
      optional_dual_tree_public_inputs: BytesLike[],
      merkle_root_index: BigNumberish
    ],
    [ProvingStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "dryrun_validate_timestamp"
  ): TypedContractMethod<
    [
      state: ProvingStateStruct,
      output_proof_index: BigNumberish,
      output_index: BigNumberish,
      public_input_index: BigNumberish,
      timestamp_window: BigNumberish
    ],
    [ProvingStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "forced_opening_verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "has_data_stream_root"
  ): TypedContractMethod<
    [_datastream: AddressLike, _root: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "provingStates"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string, string, string] & {
        current_hash: string;
        expected_hash: string;
        current_index: bigint;
        prepared_proof: string;
        proof_verifier: string;
        initiator: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "public_proof_verifier"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
