#!/usr/bin/env node
/**
 * @nihilium/codegen
 *
 * Reads a Nihilium template (a compiled `UnsealConditionTemplateExport`, or a collection
 * export straight from the editor, which is compiled on the fly) and emits, for the unseal flow:
 *
 *   1. A types file (`--out`) — per fork, the module-id constants and a typed resolver interface
 *      listing the external inputs each module needs. Contains NO application logic, so it is safe
 *      to regenerate whenever the template changes without clobbering hand-written code.
 *
 *   2. An unsealing-client scaffold — an empty `NihiliumUnsealingClient` subclass with TODO markers
 *      at the extension points (buildResolvers / prepareProofProduction / buildProvidedProofs), wired
 *      to the generated types. This is where you implement your proving system (see the shipped
 *      ZKEmailUnsealingClient for a worked example). Because you fill it in, it is generated ONCE and
 *      never overwritten on re-run (pass --force-client to regenerate it).
 *
 * Usage:
 *   nihilium-codegen <template.json> [--out <file.generated.ts>] [--network <id>]
 *                    [--client-out <file.ts>] [--no-client] [--force-client]
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { basename } from "node:path";
import {
  StandardProofLibrary,
  StandardModuleLibrary,
  toAddressMap,
  NETWORK_IDS,
  types as nhTypes,
} from "@nihilium/core";

type IOType =
  | "Timestamp" | "BigInt" | "Number" | "String" | "HexString"
  | "Randomness" | "Other" | "Boolean" | IOType[];

type IO = { type_order: IOType[]; user_input: boolean; description: string; required: boolean };
type IOMap = { [key: string]: IO };
type CompiledModule = { module_id: string; module_name: string };

function tsTypeOf(t: IOType): string {
  if (Array.isArray(t)) return `${tsTypeOf(t[0])}[]`;
  switch (t) {
    case "BigInt": return "bigint";
    case "Number": case "Timestamp": return "number";
    case "Boolean": return "boolean";
    case "String": case "HexString": case "Randomness": return "string";
    default: return "unknown";
  }
}

function parseArgs(argv: string[]): {
  input?: string; out?: string; network: number;
  clientOut?: string; noClient: boolean; forceClient: boolean;
} {
  let input: string | undefined;
  let out: string | undefined;
  let clientOut: string | undefined;
  let noClient = false;
  let forceClient = false;
  let network = NETWORK_IDS.ANVIL;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--out" || a === "-o") out = argv[++i];
    else if (a === "--client-out") clientOut = argv[++i];
    else if (a === "--no-client") noClient = true;
    else if (a === "--force-client") forceClient = true;
    else if (a === "--network" || a === "-n") network = Number(argv[++i]);
    else if (!a.startsWith("-")) input = a;
  }
  return { input, out, network, clientOut, noClient, forceClient };
}

/** Resolve the per-fork compiled module lists, compiling a collection export if needed. */
function compiledForks(raw: any, network: number): CompiledModule[][] {
  if (raw?.compiled_collection?.compiled_modules) {
    return raw.compiled_collection.compiled_modules as CompiledModule[][];
  }
  // Collection export from the editor: build + compile it to obtain the compiled modules.
  const proofLibrary = new StandardProofLibrary();
  const moduleLibrary = new StandardModuleLibrary();
  const Collection = (nhTypes as any).UnsealConditionCollection;
  const collection = new Collection(raw.name ?? "collection", raw.description ?? "", proofLibrary, moduleLibrary);
  collection.import_from_json(raw);
  const template = collection.createTemplate(toAddressMap(network));
  return template.compiled_collection.compiled_modules as CompiledModule[][];
}

/** Modules of a fork that declare external (resolver-supplied) inputs, with those inputs. */
function modulesNeedingInputs(
  modules: CompiledModule[],
  moduleLibrary: StandardModuleLibrary,
  proofLibrary: StandardProofLibrary,
): { module: CompiledModule; inputs: IOMap }[] {
  const out: { module: CompiledModule; inputs: IOMap }[] = [];
  for (const module of modules) {
    const mod = moduleLibrary.getModule(module.module_name, proofLibrary) as unknown as { productionInputs(): IOMap };
    const inputs = mod.productionInputs();
    if (Object.keys(inputs).length > 0) out.push({ module, inputs });
  }
  return out;
}

function generate(forks: CompiledModule[][], source: string): string {
  const proofLibrary = new StandardProofLibrary();
  const moduleLibrary = new StandardModuleLibrary();

  const lines: string[] = [];
  lines.push(`// AUTO-GENERATED by @nihilium/codegen from "${source}". Do not edit.`);
  lines.push(`// Re-run codegen to update. This file contains only constants and types —`);
  lines.push(`// implement the resolvers in your unsealing client so regeneration never clobbers them.`);
  lines.push(``);

  forks.forEach((modules, forkIndex) => {
    // module-id constants
    lines.push(`/** Module ids for fork ${forkIndex}. */`);
    lines.push(`export const Fork${forkIndex}ModuleIds = {`);
    for (const m of modules) lines.push(`  ${JSON.stringify(m.module_id)}: ${JSON.stringify(m.module_id)},`);
    lines.push(`} as const;`);
    lines.push(``);

    // typed resolver interface — only modules that need external inputs
    const needing = modulesNeedingInputs(modules, moduleLibrary, proofLibrary);

    lines.push(`/**`);
    lines.push(` * Resolvers for fork ${forkIndex}: the external inputs each module needs to produce its proof.`);
    lines.push(` * Return an object of this shape from your unsealing client's buildResolvers() (or pass it as`);
    lines.push(` * start_unsealing(..., { resolvers })). Context-only modules are omitted.`);
    lines.push(` * A type alias (not an interface) so it is assignable to the resolver map.`);
    lines.push(` */`);
    lines.push(`export type Fork${forkIndex}Resolvers = {`);
    if (needing.length === 0) {
      lines.push(`  // No external inputs required for this fork.`);
    }
    for (const { module, inputs } of needing) {
      const fields = Object.entries(inputs)
        .map(([name, io]) => `${JSON.stringify(name)}: ${tsTypeOf(io.type_order[0])}`)
        .join("; ");
      lines.push(`  // ${module.module_name}`);
      lines.push(`  ${JSON.stringify(module.module_id)}(): Promise<{ ${fields} }>;`);
    }
    lines.push(`};`);
    lines.push(``);
  });

  return lines.join("\n");
}

/** PascalCase class-name base derived from the output/source filename. */
function deriveClientName(source: string, out?: string): string {
  const raw = basename(out ?? source)
    .replace(/\.ts$/, "")
    .replace(/\.json$/, "")
    .replace(/\.(bindings|generated)/g, "");
  const pascal = raw.split(/[^a-zA-Z0-9]+/).filter(Boolean)
    .map((s) => s[0].toUpperCase() + s.slice(1)).join("");
  return (pascal || "Generated") + "UnsealingClient";
}

/**
 * Emit an empty `NihiliumUnsealingClient` subclass scaffold for fork 0: the framework + TODO markers at
 * the extension points, wired to the generated types. This is where the application implements its
 * proving system. Only fork 0 (the default proofIndex) is scaffolded.
 */
function generateUnsealingClient(
  forks: CompiledModule[][],
  source: string,
  className: string,
  typesImportSpec: string,
): string {
  const proofLibrary = new StandardProofLibrary();
  const moduleLibrary = new StandardModuleLibrary();
  const fork0 = forks[0] ?? [];
  const needing = modulesNeedingInputs(fork0, moduleLibrary, proofLibrary);

  const lines: string[] = [];
  lines.push(`// SCAFFOLD generated by @nihilium/codegen from "${source}".`);
  lines.push(`// This is an EMPTY FRAMEWORK for you to fill in — implement the TODOs below.`);
  lines.push(`// Re-running codegen will NOT overwrite this file (pass --force-client to regenerate).`);
  lines.push(``);
  // Only import the generated symbols we actually reference, to avoid unused-import noise.
  if (needing.length > 0) {
    lines.push(`import { NihiliumUnsealingClient, UnsealResolvers } from "@nihilium/core";`);
    lines.push(`import { Fork0ModuleIds, Fork0Resolvers } from "${typesImportSpec}";`);
  } else {
    lines.push(`import { NihiliumUnsealingClient, UnsealResolvers } from "@nihilium/core";`);
  }
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Unsealing client for fork 0 of "${source}".`);
  lines.push(` *`);
  lines.push(` * Extend the base's hooks to plug in your proving system. See ZKEmailUnsealingClient in`);
  lines.push(` * @nihilium/core for a complete worked example.`);
  lines.push(` *`);
  lines.push(` *  - prepareProofProduction(): one-time setup before proofs are produced (after reveal values`);
  lines.push(` *    are published) — e.g. request an external proof and await it. Persist any inputs via`);
  lines.push(` *    setScenarioState(...) so a resume reuses them.`);
  lines.push(` *  - buildResolvers(): supply each module's external inputs (the TODOs below).`);
  lines.push(` *  - buildProvidedProofs(): optionally inject already-produced module proofs.`);
  lines.push(` */`);
  lines.push(`export class ${className} extends NihiliumUnsealingClient {`);
  lines.push(``);
  lines.push(`  // One-time setup before proof production. Optional — uncomment to use.`);
  lines.push(`  // Runs after reveal values are published and before any proofs are produced.`);
  lines.push(`  // protected async prepareProofProduction(processorIndices: number[]): Promise<void> {`);
  lines.push(`  //   // TODO: kick off any out-of-band work your scenario needs (e.g. request a proof),`);
  lines.push(`  //   //       and persist inputs so a resume reuses them:`);
  lines.push(`  //   // await this.setScenarioState({ /* ... */ });`);
  lines.push(`  // }`);
  lines.push(``);

  if (needing.length === 0) {
    lines.push(`  // Fork 0 has no modules that require external inputs, so there are no resolvers to`);
    lines.push(`  // implement — the base class already handles this fork. This subclass is a starting`);
    lines.push(`  // point; override the hooks above if your scenario grows to need them.`);
    lines.push(`  protected buildResolvers(): UnsealResolvers {`);
    lines.push(`    return {};`);
    lines.push(`  }`);
  } else {
    lines.push(`  /**`);
    lines.push(`   * Supply the external inputs each module needs to produce its proof, keyed by module id.`);
    lines.push(`   * TODO: implement each resolver below (replace the thrown errors with real inputs).`);
    lines.push(`   */`);
    lines.push(`  protected buildResolvers(): UnsealResolvers {`);
    lines.push(`    const resolvers: Fork0Resolvers = {`);
    for (const { module, inputs } of needing) {
      const fieldList = Object.keys(inputs).join(", ");
      lines.push(`      // ${module.module_name} — needs: ${fieldList}`);
      lines.push(`      [Fork0ModuleIds[${JSON.stringify(module.module_id)}]]: async () => {`);
      lines.push(`        // TODO: produce and return { ${fieldList} } for ${module.module_name}.`);
      lines.push(`        throw new Error("TODO: implement resolver for ${module.module_id}");`);
      lines.push(`      },`);
    }
    lines.push(`    };`);
    lines.push(`    return resolvers;`);
    lines.push(`  }`);
  }

  lines.push(`}`);
  lines.push(``);
  return lines.join("\n");
}

function main(): void {
  const { input, out, network, clientOut, noClient, forceClient } = parseArgs(process.argv.slice(2));
  if (!input) {
    console.error(
      "Usage: nihilium-codegen <template.json> [--out <file.generated.ts>] [--network <id>] " +
      "[--client-out <file.ts>] [--no-client] [--force-client]",
    );
    process.exit(1);
  }
  const raw = JSON.parse(readFileSync(input, "utf8"));
  const forks = compiledForks(raw, network);

  const typesCode = generate(forks, input);
  const className = deriveClientName(input, out);

  if (out) {
    writeFileSync(out, typesCode);
    console.error(`Wrote ${out} (${forks.length} fork(s))`);

    if (!noClient) {
      // Derive a sibling scaffold path + the import spec pointing at the generated types file.
      const clientPath = clientOut ?? out.replace(/(\.bindings)?(\.generated)?\.ts$/, ".unsealing-client.ts");
      const typesImportSpec = "./" + basename(out).replace(/\.ts$/, "");
      const clientCode = generateUnsealingClient(forks, input, className, typesImportSpec);
      if (existsSync(clientPath) && !forceClient) {
        console.error(`Skipped ${clientPath} (already exists; pass --force-client to overwrite)`);
      } else {
        writeFileSync(clientPath, clientCode);
        console.error(`Wrote ${clientPath} (class ${className})`);
      }
    }
  } else {
    // stdout mode: print the types, then the scaffold (import spec is a placeholder for preview).
    process.stdout.write(typesCode);
    if (!noClient) {
      process.stdout.write(`\n// ---- unsealing client scaffold ----\n`);
      process.stdout.write(generateUnsealingClient(forks, input, className, "./bindings.generated"));
    }
  }
}

main();
