#!/usr/bin/env node
/**
 * @nihilium/codegen
 *
 * Reads a Nihilium template (a compiled `UnsealConditionTemplateExport`, or a collection
 * export straight from the editor, which is compiled on the fly) and emits typed resolver
 * scaffolding for the unseal fork driver: per fork, the module-id constants and a typed
 * resolver interface listing the external inputs each module needs.
 *
 * The generated file holds NO application logic (only constants + interfaces), so it is safe
 * to regenerate whenever the template changes without clobbering hand-written resolver bodies.
 *
 * Usage:
 *   nihilium-codegen <template.json> [--out <file.generated.ts>] [--network <id>]
 */

import { readFileSync, writeFileSync } from "node:fs";
import {
  StandardProofLibrary,
  StandardModuleLibrary,
  toAddressMap,
  NETWORK_IDS,
  types as nhTypes,
} from "@nihilium/core";

type IOType =
  | "Timestamp" | "BigInt" | "Number" | "String" | "HexString"
  | "Randomness" | "Other" | "Boolean" | IOType[];

type IO = { type_order: IOType[]; user_input: boolean; description: string; required: boolean };
type IOMap = { [key: string]: IO };
type CompiledModule = { module_id: string; module_name: string };

function tsTypeOf(t: IOType): string {
  if (Array.isArray(t)) return `${tsTypeOf(t[0])}[]`;
  switch (t) {
    case "BigInt": return "bigint";
    case "Number": case "Timestamp": return "number";
    case "Boolean": return "boolean";
    case "String": case "HexString": case "Randomness": return "string";
    default: return "unknown";
  }
}

function parseArgs(argv: string[]): { input?: string; out?: string; network: number } {
  let input: string | undefined;
  let out: string | undefined;
  let network = NETWORK_IDS.ANVIL;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--out" || a === "-o") out = argv[++i];
    else if (a === "--network" || a === "-n") network = Number(argv[++i]);
    else if (!a.startsWith("-")) input = a;
  }
  return { input, out, network };
}

/** Resolve the per-fork compiled module lists, compiling a collection export if needed. */
function compiledForks(raw: any, network: number): CompiledModule[][] {
  if (raw?.compiled_collection?.compiled_modules) {
    return raw.compiled_collection.compiled_modules as CompiledModule[][];
  }
  // Collection export from the editor: build + compile it to obtain the compiled modules.
  const proofLibrary = new StandardProofLibrary();
  const moduleLibrary = new StandardModuleLibrary();
  const Collection = (nhTypes as any).UnsealConditionCollection;
  const collection = new Collection(raw.name ?? "collection", raw.description ?? "", proofLibrary, moduleLibrary);
  collection.import_from_json(raw);
  const template = collection.createTemplate(toAddressMap(network));
  return template.compiled_collection.compiled_modules as CompiledModule[][];
}

function generate(forks: CompiledModule[][], source: string): string {
  const proofLibrary = new StandardProofLibrary();
  const moduleLibrary = new StandardModuleLibrary();

  const lines: string[] = [];
  lines.push(`// AUTO-GENERATED by @nihilium/codegen from "${source}". Do not edit.`);
  lines.push(`// Re-run codegen to update. This file contains only constants and types —`);
  lines.push(`// implement the resolvers in your own file so regeneration never clobbers them.`);
  lines.push(``);

  forks.forEach((modules, forkIndex) => {
    // module-id constants
    lines.push(`/** Module ids for fork ${forkIndex}. */`);
    lines.push(`export const Fork${forkIndex}ModuleIds = {`);
    for (const m of modules) lines.push(`  ${JSON.stringify(m.module_id)}: ${JSON.stringify(m.module_id)},`);
    lines.push(`} as const;`);
    lines.push(``);

    // typed resolver interface — only modules that need external inputs
    const needing = modules.filter((m) => {
      const mod = moduleLibrary.getModule(m.module_name, proofLibrary) as unknown as { productionInputs(): IOMap };
      return Object.keys(mod.productionInputs()).length > 0;
    });

    lines.push(`/**`);
    lines.push(` * Resolvers for fork ${forkIndex}. Pass an object implementing this to`);
    lines.push(` * unsealingProcess.runPath(${forkIndex}, resolvers). Context-only modules are omitted.`);
    lines.push(` * A type alias (not an interface) so it is assignable to runPath's resolver map.`);
    lines.push(` */`);
    lines.push(`export type Fork${forkIndex}Resolvers = {`);
    if (needing.length === 0) {
      lines.push(`  // No external inputs required for this fork — call runPath(${forkIndex}) with {}.`);
    }
    for (const m of needing) {
      const mod = moduleLibrary.getModule(m.module_name, proofLibrary) as unknown as { productionInputs(): IOMap };
      const inputs = mod.productionInputs();
      const fields = Object.entries(inputs)
        .map(([name, io]) => `${JSON.stringify(name)}: ${tsTypeOf(io.type_order[0])}`)
        .join("; ");
      lines.push(`  // ${m.module_name}`);
      lines.push(`  ${JSON.stringify(m.module_id)}(): Promise<{ ${fields} }>;`);
    }
    lines.push(`};`);
    lines.push(``);
  });

  return lines.join("\n");
}

function main(): void {
  const { input, out, network } = parseArgs(process.argv.slice(2));
  if (!input) {
    console.error("Usage: nihilium-codegen <template.json> [--out <file.generated.ts>] [--network <id>]");
    process.exit(1);
  }
  const raw = JSON.parse(readFileSync(input, "utf8"));
  const forks = compiledForks(raw, network);
  const code = generate(forks, input);
  if (out) {
    writeFileSync(out, code);
    console.error(`Wrote ${out} (${forks.length} fork(s))`);
  } else {
    process.stdout.write(code);
  }
}

main();
