/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  Between,
  BetweenInterface,
} from "../../../contracts/proofs/Between";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "publicSignals",
        type: "bytes32[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506102268061001f6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063ea50d0e414610030575b600080fd5b61004361003e3660046100f1565b610057565b604051901515815260200160405180910390f35b600060038214610069576100696101c4565b8282600181811061007c5761007c6101da565b9050602002013560001c83836000818110610099576100996101da565b9050602002013560001c101580156100e85750828260028181106100bf576100bf6101da565b9050602002013560001c838360008181106100dc576100dc6101da565b9050602002013560001c105b95945050505050565b6000806000806040858703121561010757600080fd5b843567ffffffffffffffff81111561011e57600080fd5b8501601f8101871361012f57600080fd5b803567ffffffffffffffff81111561014657600080fd5b87602082840101111561015857600080fd5b60209182019550935085013567ffffffffffffffff81111561017957600080fd5b8501601f8101871361018a57600080fd5b803567ffffffffffffffff8111156101a157600080fd5b8760208260051b84010111156101b657600080fd5b949793965060200194505050565b634e487b7160e01b600052600160045260246000fd5b634e487b7160e01b600052603260045260246000fdfea26469706673582212204af91080669537c705ed4a0162bbd61e1a9d428a22809062248a64f054b4427e64736f6c634300081b0033";

type BetweenConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BetweenConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Between__factory extends ContractFactory {
  constructor(...args: BetweenConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Between & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Between__factory {
    return super.connect(runner) as Between__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BetweenInterface {
    return new Interface(_abi) as BetweenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Between {
    return new Contract(address, _abi, runner) as unknown as Between;
  }
}
