/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  KeccakTreeEntry,
  KeccakTreeEntryInterface,
} from "../../../contracts/proofs/KeccakTreeEntry";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "publicSignals",
        type: "bytes32[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b506102078061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610029575f3560e01c8063ea50d0e41461002d575b5f5ffd5b61004061003b3660046100e1565b610054565b604051901515815260200160405180910390f35b5f60028214610065576100656101a9565b8315610073576100736101a9565b82826001818110610086576100866101bd565b9050602002013583835f81811061009f5761009f6101bd565b6040516100c0936020928302013592505f9101918252602082015260400190565b60405160208183030381529060405280519060200120149050949350505050565b5f5f5f5f604085870312156100f4575f5ffd5b843567ffffffffffffffff81111561010a575f5ffd5b8501601f8101871361011a575f5ffd5b803567ffffffffffffffff811115610130575f5ffd5b876020828401011115610141575f5ffd5b60209182019550935085013567ffffffffffffffff811115610161575f5ffd5b8501601f81018713610171575f5ffd5b803567ffffffffffffffff811115610187575f5ffd5b8760208260051b840101111561019b575f5ffd5b949793965060200194505050565b634e487b7160e01b5f52600160045260245ffd5b634e487b7160e01b5f52603260045260245ffdfea264697066735822122017c14ab280443112e4c8f56a7399671a9630efd059e3d96125ca3c9d3517861964736f6c634300081b0033";

type KeccakTreeEntryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: KeccakTreeEntryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class KeccakTreeEntry__factory extends ContractFactory {
  constructor(...args: KeccakTreeEntryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      KeccakTreeEntry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): KeccakTreeEntry__factory {
    return super.connect(runner) as KeccakTreeEntry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): KeccakTreeEntryInterface {
    return new Interface(_abi) as KeccakTreeEntryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): KeccakTreeEntry {
    return new Contract(address, _abi, runner) as unknown as KeccakTreeEntry;
  }
}
