/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ManualChoice,
  ManualChoiceInterface,
} from "../../../contracts/proofs/ManualChoice";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "publicSignals",
        type: "bytes32[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b506101c18061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610029575f3560e01c8063ea50d0e41461002d575b5f5ffd5b61004061003b36600461009b565b610054565b604051901515815260200160405180910390f35b5f6001821461006557610065610163565b831561007357610073610163565b82825f81811061008557610085610177565b905060200201355f1c6001149050949350505050565b5f5f5f5f604085870312156100ae575f5ffd5b843567ffffffffffffffff8111156100c4575f5ffd5b8501601f810187136100d4575f5ffd5b803567ffffffffffffffff8111156100ea575f5ffd5b8760208284010111156100fb575f5ffd5b60209182019550935085013567ffffffffffffffff81111561011b575f5ffd5b8501601f8101871361012b575f5ffd5b803567ffffffffffffffff811115610141575f5ffd5b8760208260051b8401011115610155575f5ffd5b949793965060200194505050565b634e487b7160e01b5f52600160045260245ffd5b634e487b7160e01b5f52603260045260245ffdfea264697066735822122069265cfc046807ef2bf31310a75fef62fcae8a3ff2b1f6b6219eb9c1113369f664736f6c634300081b0033";

type ManualChoiceConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ManualChoiceConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ManualChoice__factory extends ContractFactory {
  constructor(...args: ManualChoiceConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ManualChoice & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ManualChoice__factory {
    return super.connect(runner) as ManualChoice__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ManualChoiceInterface {
    return new Interface(_abi) as ManualChoiceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ManualChoice {
    return new Contract(address, _abi, runner) as unknown as ManualChoice;
  }
}
