/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  TimeBetweenOffsetProof,
  TimeBetweenOffsetProofInterface,
} from "../../../contracts/proofs/TimeBetweenOffsetProof";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "publicSignals",
        type: "bytes32[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506102738061001f6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063ea50d0e414610030575b600080fd5b61004361003e366004610117565b610057565b604051901515815260200160405180910390f35b600060038214610069576100696101ea565b8282600181811061007c5761007c610200565b9050602002013560001c8383600081811061009957610099610200565b9050602002013560001c11801561010e5750828260028181106100be576100be610200565b9050602002013560001c838360018181106100db576100db610200565b9050602002013560001c6100ef9190610216565b8383600081811061010257610102610200565b9050602002013560001c105b95945050505050565b6000806000806040858703121561012d57600080fd5b843567ffffffffffffffff81111561014457600080fd5b8501601f8101871361015557600080fd5b803567ffffffffffffffff81111561016c57600080fd5b87602082840101111561017e57600080fd5b60209182019550935085013567ffffffffffffffff81111561019f57600080fd5b8501601f810187136101b057600080fd5b803567ffffffffffffffff8111156101c757600080fd5b8760208260051b84010111156101dc57600080fd5b949793965060200194505050565b634e487b7160e01b600052600160045260246000fd5b634e487b7160e01b600052603260045260246000fd5b8082018082111561023757634e487b7160e01b600052601160045260246000fd5b9291505056fea264697066735822122095e698066c18527a23632905f7d9a57717543aa94b4196f3633e804e4a8ed13964736f6c634300081b0033";

type TimeBetweenOffsetProofConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TimeBetweenOffsetProofConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TimeBetweenOffsetProof__factory extends ContractFactory {
  constructor(...args: TimeBetweenOffsetProofConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TimeBetweenOffsetProof & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): TimeBetweenOffsetProof__factory {
    return super.connect(runner) as TimeBetweenOffsetProof__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TimeBetweenOffsetProofInterface {
    return new Interface(_abi) as TimeBetweenOffsetProofInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TimeBetweenOffsetProof {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as TimeBetweenOffsetProof;
  }
}
