# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application's source code from your context
COPY . .

# Copy privacy-lib
COPY ../privacy-lib ./privacy-lib

# Build the TypeScript code
RUN npm run build

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Define environment variables with default values
ENV PRIVATE_KEY=""
ENV CONTRACT_ADDRESS=""
ENV RPC_URL=""
ENV PORT=3000

# Run the app when the container launches
CMD ["node", "dist/server.js"] 