/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  HashFunction,
  HashFunctionInterface,
} from "../../../contracts/ChainedProof.sol/HashFunction";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "inputs",
        type: "bytes32[]",
      },
    ],
    name: "hash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class HashFunction__factory {
  static readonly abi = _abi;
  static createInterface(): HashFunctionInterface {
    return new Interface(_abi) as HashFunctionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): HashFunction {
    return new Contract(address, _abi, runner) as unknown as HashFunction;
  }
}
