/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface LearnedCallProxyProofInterface extends Interface {
  getFunction(
    nameOrSignature: "bannedAt" | "verifiers" | "verify"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BanRecorded" | "VerifierLearned"
  ): EventFragment;

  encodeFunctionData(functionFragment: "bannedAt", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "verifiers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(functionFragment: "bannedAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifiers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace BanRecordedEvent {
  export type InputTuple = [key: BytesLike, at: BigNumberish];
  export type OutputTuple = [key: string, at: bigint];
  export interface OutputObject {
    key: string;
    at: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierLearnedEvent {
  export type InputTuple = [key: BytesLike, verifier: AddressLike];
  export type OutputTuple = [key: string, verifier: string];
  export interface OutputObject {
    key: string;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LearnedCallProxyProof extends BaseContract {
  connect(runner?: ContractRunner | null): LearnedCallProxyProof;
  waitForDeployment(): Promise<this>;

  interface: LearnedCallProxyProofInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bannedAt: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  verifiers: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  verify: TypedContractMethod<
    [_proof: BytesLike, _publicInputs: BytesLike[]],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bannedAt"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifiers"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [_proof: BytesLike, _publicInputs: BytesLike[]],
    [boolean],
    "view"
  >;

  getEvent(
    key: "BanRecorded"
  ): TypedContractEvent<
    BanRecordedEvent.InputTuple,
    BanRecordedEvent.OutputTuple,
    BanRecordedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierLearned"
  ): TypedContractEvent<
    VerifierLearnedEvent.InputTuple,
    VerifierLearnedEvent.OutputTuple,
    VerifierLearnedEvent.OutputObject
  >;

  filters: {
    "BanRecorded(bytes32,uint64)": TypedContractEvent<
      BanRecordedEvent.InputTuple,
      BanRecordedEvent.OutputTuple,
      BanRecordedEvent.OutputObject
    >;
    BanRecorded: TypedContractEvent<
      BanRecordedEvent.InputTuple,
      BanRecordedEvent.OutputTuple,
      BanRecordedEvent.OutputObject
    >;

    "VerifierLearned(bytes32,address)": TypedContractEvent<
      VerifierLearnedEvent.InputTuple,
      VerifierLearnedEvent.OutputTuple,
      VerifierLearnedEvent.OutputObject
    >;
    VerifierLearned: TypedContractEvent<
      VerifierLearnedEvent.InputTuple,
      VerifierLearnedEvent.OutputTuple,
      VerifierLearnedEvent.OutputObject
    >;
  };
}
