/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeCast__factory>;
    getContractFactory(
      name: "Strings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Strings__factory>;
    getContractFactory(
      name: "ChainedProof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ChainedProof__factory>;
    getContractFactory(
      name: "HashFunction",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HashFunction__factory>;
    getContractFactory(
      name: "EmpheralMerkleTreeKeccak",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EmpheralMerkleTreeKeccak__factory>;
    getContractFactory(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BaseHonkVerifier__factory>;
    getContractFactory(
      name: "Encrypt_proof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Encrypt_proof__factory>;
    getContractFactory(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifier__factory>;
    getContractFactory(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BaseHonkVerifier__factory>;
    getContractFactory(
      name: "Generic_adjacent_tree_proof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Generic_adjacent_tree_proof__factory>;
    getContractFactory(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifier__factory>;
    getContractFactory(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BaseHonkVerifier__factory>;
    getContractFactory(
      name: "Generic_tree_proof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Generic_tree_proof__factory>;
    getContractFactory(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifier__factory>;
    getContractFactory(
      name: "IDataStream",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDataStream__factory>;
    getContractFactory(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifier__factory>;
    getContractFactory(
      name: "NihiliumRecoveryRegister",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NihiliumRecoveryRegister__factory>;
    getContractFactory(
      name: "Opening_proof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Opening_proof__factory>;
    getContractFactory(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BaseHonkVerifier__factory>;
    getContractFactory(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifier__factory>;
    getContractFactory(
      name: "Sub_tree_merkle_proof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Sub_tree_merkle_proof__factory>;
    getContractFactory(
      name: "SubTreeMerkleProof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SubTreeMerkleProof__factory>;
    getContractFactory(
      name: "TestVerifyAlwaysTrue",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestVerifyAlwaysTrue__factory>;
    getContractFactory(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BaseHonkVerifier__factory>;
    getContractFactory(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifier__factory>;
    getContractFactory(
      name: "Top_level_merkle_proof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Top_level_merkle_proof__factory>;
    getContractFactory(
      name: "TopLevelMerkleProof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TopLevelMerkleProof__factory>;
    getContractFactory(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BaseHonkVerifier__factory>;
    getContractFactory(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifier__factory>;
    getContractFactory(
      name: "Validated_sig_he_add",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Validated_sig_he_add__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "SafeCast",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeCast>;
    getContractAt(
      name: "Strings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Strings>;
    getContractAt(
      name: "ChainedProof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ChainedProof>;
    getContractAt(
      name: "HashFunction",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HashFunction>;
    getContractAt(
      name: "EmpheralMerkleTreeKeccak",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EmpheralMerkleTreeKeccak>;
    getContractAt(
      name: "BaseHonkVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BaseHonkVerifier>;
    getContractAt(
      name: "Encrypt_proof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Encrypt_proof>;
    getContractAt(
      name: "IVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifier>;
    getContractAt(
      name: "BaseHonkVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BaseHonkVerifier>;
    getContractAt(
      name: "Generic_adjacent_tree_proof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Generic_adjacent_tree_proof>;
    getContractAt(
      name: "IVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifier>;
    getContractAt(
      name: "BaseHonkVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BaseHonkVerifier>;
    getContractAt(
      name: "Generic_tree_proof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Generic_tree_proof>;
    getContractAt(
      name: "IVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifier>;
    getContractAt(
      name: "IDataStream",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDataStream>;
    getContractAt(
      name: "IVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifier>;
    getContractAt(
      name: "NihiliumRecoveryRegister",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.NihiliumRecoveryRegister>;
    getContractAt(
      name: "Opening_proof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Opening_proof>;
    getContractAt(
      name: "BaseHonkVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BaseHonkVerifier>;
    getContractAt(
      name: "IVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifier>;
    getContractAt(
      name: "Sub_tree_merkle_proof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Sub_tree_merkle_proof>;
    getContractAt(
      name: "SubTreeMerkleProof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SubTreeMerkleProof>;
    getContractAt(
      name: "TestVerifyAlwaysTrue",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TestVerifyAlwaysTrue>;
    getContractAt(
      name: "BaseHonkVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BaseHonkVerifier>;
    getContractAt(
      name: "IVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifier>;
    getContractAt(
      name: "Top_level_merkle_proof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Top_level_merkle_proof>;
    getContractAt(
      name: "TopLevelMerkleProof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TopLevelMerkleProof>;
    getContractAt(
      name: "BaseHonkVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BaseHonkVerifier>;
    getContractAt(
      name: "IVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifier>;
    getContractAt(
      name: "Validated_sig_he_add",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Validated_sig_he_add>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "Strings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "ChainedProof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ChainedProof>;
    deployContract(
      name: "HashFunction",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HashFunction>;
    deployContract(
      name: "EmpheralMerkleTreeKeccak",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmpheralMerkleTreeKeccak>;
    deployContract(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "Encrypt_proof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Encrypt_proof>;
    deployContract(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "Generic_adjacent_tree_proof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Generic_adjacent_tree_proof>;
    deployContract(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "Generic_tree_proof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Generic_tree_proof>;
    deployContract(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "IDataStream",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDataStream>;
    deployContract(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "NihiliumRecoveryRegister",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NihiliumRecoveryRegister>;
    deployContract(
      name: "Opening_proof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Opening_proof>;
    deployContract(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "Sub_tree_merkle_proof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Sub_tree_merkle_proof>;
    deployContract(
      name: "SubTreeMerkleProof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SubTreeMerkleProof>;
    deployContract(
      name: "TestVerifyAlwaysTrue",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestVerifyAlwaysTrue>;
    deployContract(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "Top_level_merkle_proof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Top_level_merkle_proof>;
    deployContract(
      name: "TopLevelMerkleProof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TopLevelMerkleProof>;
    deployContract(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "Validated_sig_he_add",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Validated_sig_he_add>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "SafeCast",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "Strings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "ChainedProof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ChainedProof>;
    deployContract(
      name: "HashFunction",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HashFunction>;
    deployContract(
      name: "EmpheralMerkleTreeKeccak",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmpheralMerkleTreeKeccak>;
    deployContract(
      name: "BaseHonkVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "Encrypt_proof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Encrypt_proof>;
    deployContract(
      name: "IVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "BaseHonkVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "Generic_adjacent_tree_proof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Generic_adjacent_tree_proof>;
    deployContract(
      name: "IVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "BaseHonkVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "Generic_tree_proof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Generic_tree_proof>;
    deployContract(
      name: "IVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "IDataStream",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDataStream>;
    deployContract(
      name: "IVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "NihiliumRecoveryRegister",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NihiliumRecoveryRegister>;
    deployContract(
      name: "Opening_proof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Opening_proof>;
    deployContract(
      name: "BaseHonkVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "IVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "Sub_tree_merkle_proof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Sub_tree_merkle_proof>;
    deployContract(
      name: "SubTreeMerkleProof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SubTreeMerkleProof>;
    deployContract(
      name: "TestVerifyAlwaysTrue",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestVerifyAlwaysTrue>;
    deployContract(
      name: "BaseHonkVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "IVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "Top_level_merkle_proof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Top_level_merkle_proof>;
    deployContract(
      name: "TopLevelMerkleProof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TopLevelMerkleProof>;
    deployContract(
      name: "BaseHonkVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "IVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "Validated_sig_he_add",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Validated_sig_he_add>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
