/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface TestExpectInputsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "configured"
      | "expect"
      | "expectedFirst"
      | "expectedLength"
      | "verify"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "configured",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "expect",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "expectedFirst",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "expectedLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(functionFragment: "configured", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "expect", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "expectedFirst",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expectedLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export interface TestExpectInputs extends BaseContract {
  connect(runner?: ContractRunner | null): TestExpectInputs;
  waitForDeployment(): Promise<this>;

  interface: TestExpectInputsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  configured: TypedContractMethod<[], [boolean], "view">;

  expect: TypedContractMethod<
    [length: BigNumberish, first: BytesLike],
    [void],
    "nonpayable"
  >;

  expectedFirst: TypedContractMethod<[], [string], "view">;

  expectedLength: TypedContractMethod<[], [bigint], "view">;

  verify: TypedContractMethod<
    [arg0: BytesLike, publicInputs: BytesLike[]],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "configured"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "expect"
  ): TypedContractMethod<
    [length: BigNumberish, first: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "expectedFirst"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "expectedLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [arg0: BytesLike, publicInputs: BytesLike[]],
    [boolean],
    "view"
  >;

  filters: {};
}
