/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TopLevelMerkleProofInterface extends Interface {
  getFunction(
    nameOrSignature: "_efficientHash" | "extractBytes32List" | "verify"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_efficientHash",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "extractBytes32List",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "_efficientHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extractBytes32List",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export interface TopLevelMerkleProof extends BaseContract {
  connect(runner?: ContractRunner | null): TopLevelMerkleProof;
  waitForDeployment(): Promise<this>;

  interface: TopLevelMerkleProofInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _efficientHash: TypedContractMethod<
    [a: BytesLike, b: BytesLike],
    [string],
    "view"
  >;

  extractBytes32List: TypedContractMethod<
    [data: BytesLike],
    [string[]],
    "view"
  >;

  verify: TypedContractMethod<
    [proof: BytesLike, publicSignals: BytesLike[]],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_efficientHash"
  ): TypedContractMethod<[a: BytesLike, b: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "extractBytes32List"
  ): TypedContractMethod<[data: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [proof: BytesLike, publicSignals: BytesLike[]],
    [boolean],
    "view"
  >;

  filters: {};
}
