/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IZKPassportRootVerifier__factory } from "./IZKPassportRootVerifier__factory";
export { ZKPassportProof__factory } from "./ZKPassportProof__factory";
