/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZKPassportRootVerifier,
  IZKPassportRootVerifierInterface,
} from "../../../../contracts/proofs/ZKPassportProof.sol/IZKPassportRootVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "version",
        type: "bytes32",
      },
    ],
    name: "getSubVerifier",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZKPassportRootVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IZKPassportRootVerifierInterface {
    return new Interface(_abi) as IZKPassportRootVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IZKPassportRootVerifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IZKPassportRootVerifier;
  }
}
