/**
 * Key generation
 *
 * Mints fresh Baby Jubjub private keys for the processor's homomorphic
 * encryption (ECElGamal) keys, using the same 248-bit RNG the protocol uses
 * everywhere else (`cryptoTools.generateRandom248BitNumber`). Staying at 248
 * bits keeps every scalar comfortably inside the BN254 field, so a generated
 * key is safe to feed to the circuits as-is.
 *
 * Pure functions — no terminal I/O. Secrets are returned to the caller, which
 * is responsible for routing them to the clipboard or a file, never to stdout.
 */

import { cryptoTools, deriveHEPublicKey } from "@nihilium/zkp-circuits";
import { keyId as computeKeyId } from "@nihilium/registry";
import { writeFileSync } from "node:fs";

export interface GeneratedKey {
  /** 0x-prefixed, zero-padded to 32 bytes. SECRET — never print this. */
  privateKey: string;
  x:          bigint;
  y:          bigint;
  /** keccak256(x ++ y) — the id the registry contract stores. */
  keyId:      string;
}

/** Render a 248-bit scalar as a full-width 32-byte hex string. */
function toHex32(value: bigint): string {
  return "0x" + value.toString(16).padStart(64, "0");
}

/** Generate one HE (ECElGamal) keypair and derive its public coordinates. */
export function generateHEKey(): GeneratedKey {
  const privateKey = toHex32(cryptoTools.generateRandom248BitNumber());
  const [x, y] = deriveHEPublicKey(privateKey);
  return { privateKey, x, y, keyId: computeKeyId(x, y) };
}

/**
 * Generate one raw Baby Jubjub private scalar (248-bit, 0x-padded to 32 bytes),
 * suitable for use as an EdDSA signing private key. Only the secret is returned;
 * the public key is derived downstream (see cryptoTools.deriveSigningPublicKey).
 */
export function generateSigningPrivateKey(): string {
  return toHex32(cryptoTools.generateRandom248BitNumber());
}

export function generateHEKeys(count: number): GeneratedKey[] {
  return Array.from({ length: count }, () => generateHEKey());
}

/**
 * The exact value to paste into `PROCESSOR_HE_PRIVATE_KEYS` — the env var takes
 * a comma-separated list, which is also the shape `splitKeys()` in config.ts
 * parses back out.
 */
export function formatPrivateKeysForEnv(keys: GeneratedKey[]): string {
  return keys.map((k) => k.privateKey).join(",");
}

/**
 * Fallback for headless machines with no clipboard: write the keys to a file
 * created 0600 so they are not world-readable even for an instant.
 */
export function writePrivateKeysToFile(keys: GeneratedKey[], path: string): void {
  const body =
    `# Generated by registry-manager — move this into your .env and delete this file.\n` +
    `PROCESSOR_HE_PRIVATE_KEYS=${formatPrivateKeysForEnv(keys)}\n`;
  writeFileSync(path, body, { mode: 0o600 });
}
