depth = ""
index_bits = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
leaf_value = ""
path = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
root = ""
