/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  HashFunctionV2,
  HashFunctionV2Interface,
} from "../../../contracts/ChainedProofV2.sol/HashFunctionV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "inputs",
        type: "bytes32[]",
      },
    ],
    name: "hash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class HashFunctionV2__factory {
  static readonly abi = _abi;
  static createInterface(): HashFunctionV2Interface {
    return new Interface(_abi) as HashFunctionV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): HashFunctionV2 {
    return new Contract(address, _abi, runner) as unknown as HashFunctionV2;
  }
}
