/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface DualMerkleTreeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FIELD_SIZE"
      | "ROOT_HISTORY_SIZE"
      | "ROOT_TIME_SLIPPAGE_IN_SECONDS"
      | "ZERO_VALUE"
      | "currentRootIndex"
      | "filledValueSubtrees"
      | "filledmerkleRootSubtrees"
      | "getLastMerkleRoot"
      | "getLastValueRoot"
      | "hashLeftRightPos"
      | "iToHex"
      | "insert"
      | "isKnownMerkleRoot"
      | "isKnownValueRoot"
      | "levels"
      | "maxValue"
      | "merkleRootTimestamps"
      | "merkleRoots"
      | "nextIndex"
      | "owner"
      | "renounceOwnership"
      | "stopTree"
      | "transferOwnership"
      | "treeHasher"
      | "treeStopped"
      | "valueRootTimestamps"
      | "valueRoots"
      | "zeros"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Log" | "OwnershipTransferred" | "TreeUpdate"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FIELD_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROOT_HISTORY_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROOT_TIME_SLIPPAGE_IN_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ZERO_VALUE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentRootIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "filledValueSubtrees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "filledmerkleRootSubtrees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastMerkleRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastValueRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hashLeftRightPos",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "iToHex", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "insert",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isKnownMerkleRoot",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isKnownValueRoot",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "levels", values?: undefined): string;
  encodeFunctionData(functionFragment: "maxValue", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "merkleRootTimestamps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRoots",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nextIndex", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "stopTree", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treeHasher",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "treeStopped",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "valueRootTimestamps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "valueRoots",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "zeros", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "FIELD_SIZE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ROOT_HISTORY_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROOT_TIME_SLIPPAGE_IN_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ZERO_VALUE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentRootIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "filledValueSubtrees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "filledmerkleRootSubtrees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastValueRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashLeftRightPos",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "iToHex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "insert", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isKnownMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isKnownValueRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "levels", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxValue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "merkleRootTimestamps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merkleRoots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextIndex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stopTree", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treeHasher", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "treeStopped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "valueRootTimestamps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "valueRoots", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "zeros", data: BytesLike): Result;
}

export namespace LogEvent {
  export type InputTuple = [
    value1: BytesLike,
    value2: BytesLike,
    value3: BigNumberish
  ];
  export type OutputTuple = [value1: string, value2: string, value3: bigint];
  export interface OutputObject {
    value1: string;
    value2: string;
    value3: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreeUpdateEvent {
  export type InputTuple = [
    commitment: BigNumberish,
    leafIndex: BigNumberish,
    depositAddress: AddressLike,
    timestamp: BigNumberish,
    leafHash: BigNumberish,
    newValueRoot: BigNumberish,
    newMerkleRoot: BigNumberish
  ];
  export type OutputTuple = [
    commitment: bigint,
    leafIndex: bigint,
    depositAddress: string,
    timestamp: bigint,
    leafHash: bigint,
    newValueRoot: bigint,
    newMerkleRoot: bigint
  ];
  export interface OutputObject {
    commitment: bigint;
    leafIndex: bigint;
    depositAddress: string;
    timestamp: bigint;
    leafHash: bigint;
    newValueRoot: bigint;
    newMerkleRoot: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DualMerkleTree extends BaseContract {
  connect(runner?: ContractRunner | null): DualMerkleTree;
  waitForDeployment(): Promise<this>;

  interface: DualMerkleTreeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FIELD_SIZE: TypedContractMethod<[], [bigint], "view">;

  ROOT_HISTORY_SIZE: TypedContractMethod<[], [bigint], "view">;

  ROOT_TIME_SLIPPAGE_IN_SECONDS: TypedContractMethod<[], [bigint], "view">;

  ZERO_VALUE: TypedContractMethod<[], [bigint], "view">;

  currentRootIndex: TypedContractMethod<[], [bigint], "view">;

  filledValueSubtrees: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  filledmerkleRootSubtrees: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  getLastMerkleRoot: TypedContractMethod<[], [bigint], "view">;

  getLastValueRoot: TypedContractMethod<[], [bigint], "view">;

  hashLeftRightPos: TypedContractMethod<
    [_left: BigNumberish, _right: BigNumberish],
    [bigint],
    "view"
  >;

  iToHex: TypedContractMethod<[buffer: BytesLike], [string], "view">;

  insert: TypedContractMethod<
    [_leaf: BigNumberish, _origin: AddressLike],
    [bigint],
    "nonpayable"
  >;

  isKnownMerkleRoot: TypedContractMethod<
    [_root: BigNumberish],
    [boolean],
    "view"
  >;

  isKnownValueRoot: TypedContractMethod<
    [_root: BigNumberish],
    [boolean],
    "view"
  >;

  levels: TypedContractMethod<[], [bigint], "view">;

  maxValue: TypedContractMethod<[], [bigint], "view">;

  merkleRootTimestamps: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  merkleRoots: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  nextIndex: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  stopTree: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treeHasher: TypedContractMethod<[], [string], "view">;

  treeStopped: TypedContractMethod<[], [bigint], "view">;

  valueRootTimestamps: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  valueRoots: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  zeros: TypedContractMethod<[i: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FIELD_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROOT_HISTORY_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROOT_TIME_SLIPPAGE_IN_SECONDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ZERO_VALUE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentRootIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "filledValueSubtrees"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "filledmerkleRootSubtrees"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLastMerkleRoot"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLastValueRoot"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hashLeftRightPos"
  ): TypedContractMethod<
    [_left: BigNumberish, _right: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "iToHex"
  ): TypedContractMethod<[buffer: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "insert"
  ): TypedContractMethod<
    [_leaf: BigNumberish, _origin: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isKnownMerkleRoot"
  ): TypedContractMethod<[_root: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isKnownValueRoot"
  ): TypedContractMethod<[_root: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "levels"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "merkleRootTimestamps"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "merkleRoots"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stopTree"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treeHasher"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treeStopped"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "valueRootTimestamps"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "valueRoots"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "zeros"
  ): TypedContractMethod<[i: BigNumberish], [bigint], "view">;

  getEvent(
    key: "Log"
  ): TypedContractEvent<
    LogEvent.InputTuple,
    LogEvent.OutputTuple,
    LogEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TreeUpdate"
  ): TypedContractEvent<
    TreeUpdateEvent.InputTuple,
    TreeUpdateEvent.OutputTuple,
    TreeUpdateEvent.OutputObject
  >;

  filters: {
    "Log(bytes32,bytes32,uint256)": TypedContractEvent<
      LogEvent.InputTuple,
      LogEvent.OutputTuple,
      LogEvent.OutputObject
    >;
    Log: TypedContractEvent<
      LogEvent.InputTuple,
      LogEvent.OutputTuple,
      LogEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TreeUpdate(uint256,uint32,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TreeUpdateEvent.InputTuple,
      TreeUpdateEvent.OutputTuple,
      TreeUpdateEvent.OutputObject
    >;
    TreeUpdate: TypedContractEvent<
      TreeUpdateEvent.InputTuple,
      TreeUpdateEvent.OutputTuple,
      TreeUpdateEvent.OutputObject
    >;
  };
}
