/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeCast__factory>;
    getContractFactory(
      name: "Strings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Strings__factory>;
    getContractFactory(
      name: "ChainedProof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ChainedProof__factory>;
    getContractFactory(
      name: "HashFunction",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HashFunction__factory>;
    getContractFactory(
      name: "ChainedProofV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ChainedProofV2__factory>;
    getContractFactory(
      name: "HashFunctionV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HashFunctionV2__factory>;
    getContractFactory(
      name: "EmpheralDualMerkleTreeKeccak",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EmpheralDualMerkleTreeKeccak__factory>;
    getContractFactory(
      name: "EmpheralMerkleTreeKeccak",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EmpheralMerkleTreeKeccak__factory>;
    getContractFactory(
      name: "IDataStream",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDataStream__factory>;
    getContractFactory(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifier__factory>;
    getContractFactory(
      name: "NihiliumRecoveryRegister",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NihiliumRecoveryRegister__factory>;
    getContractFactory(
      name: "AdditionProof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AdditionProof__factory>;
    getContractFactory(
      name: "Between",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Between__factory>;
    getContractFactory(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BaseHonkVerifier__factory>;
    getContractFactory(
      name: "Email_send_no_body",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Email_send_no_body__factory>;
    getContractFactory(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifier__factory>;
    getContractFactory(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BaseHonkVerifier__factory>;
    getContractFactory(
      name: "Encrypt_proof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Encrypt_proof__factory>;
    getContractFactory(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifier__factory>;
    getContractFactory(
      name: "GreaterOrEqualThen",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GreaterOrEqualThen__factory>;
    getContractFactory(
      name: "Hash_tie",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Hash_tie__factory>;
    getContractFactory(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifier__factory>;
    getContractFactory(
      name: "KeccakPreImage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KeccakPreImage__factory>;
    getContractFactory(
      name: "KeccakTreeEntry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KeccakTreeEntry__factory>;
    getContractFactory(
      name: "ManualChoice",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ManualChoice__factory>;
    getContractFactory(
      name: "MerkleTreeProof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MerkleTreeProof__factory>;
    getContractFactory(
      name: "Opening_proof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Opening_proof__factory>;
    getContractFactory(
      name: "Poseidon2Verifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Poseidon2Verifier__factory>;
    getContractFactory(
      name: "SmallerThan",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmallerThan__factory>;
    getContractFactory(
      name: "TestVerifyAlwaysTrue",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestVerifyAlwaysTrue__factory>;
    getContractFactory(
      name: "TimeDelayProof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TimeDelayProof__factory>;
    getContractFactory(
      name: "TopLevelMerkleProof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TopLevelMerkleProof__factory>;
    getContractFactory(
      name: "ValueInjection",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ValueInjection__factory>;
    getContractFactory(
      name: "VerifyECDSA",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VerifyECDSA__factory>;
    getContractFactory(
      name: "VerifyEDDSA",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VerifyEDDSA__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "SafeCast",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeCast>;
    getContractAt(
      name: "Strings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Strings>;
    getContractAt(
      name: "ChainedProof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ChainedProof>;
    getContractAt(
      name: "HashFunction",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HashFunction>;
    getContractAt(
      name: "ChainedProofV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ChainedProofV2>;
    getContractAt(
      name: "HashFunctionV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HashFunctionV2>;
    getContractAt(
      name: "EmpheralDualMerkleTreeKeccak",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EmpheralDualMerkleTreeKeccak>;
    getContractAt(
      name: "EmpheralMerkleTreeKeccak",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EmpheralMerkleTreeKeccak>;
    getContractAt(
      name: "IDataStream",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDataStream>;
    getContractAt(
      name: "IVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifier>;
    getContractAt(
      name: "NihiliumRecoveryRegister",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.NihiliumRecoveryRegister>;
    getContractAt(
      name: "AdditionProof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AdditionProof>;
    getContractAt(
      name: "Between",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Between>;
    getContractAt(
      name: "BaseHonkVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BaseHonkVerifier>;
    getContractAt(
      name: "Email_send_no_body",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Email_send_no_body>;
    getContractAt(
      name: "IVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifier>;
    getContractAt(
      name: "BaseHonkVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BaseHonkVerifier>;
    getContractAt(
      name: "Encrypt_proof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Encrypt_proof>;
    getContractAt(
      name: "IVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifier>;
    getContractAt(
      name: "GreaterOrEqualThen",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GreaterOrEqualThen>;
    getContractAt(
      name: "Hash_tie",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Hash_tie>;
    getContractAt(
      name: "IVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifier>;
    getContractAt(
      name: "KeccakPreImage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.KeccakPreImage>;
    getContractAt(
      name: "KeccakTreeEntry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.KeccakTreeEntry>;
    getContractAt(
      name: "ManualChoice",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ManualChoice>;
    getContractAt(
      name: "MerkleTreeProof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MerkleTreeProof>;
    getContractAt(
      name: "Opening_proof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Opening_proof>;
    getContractAt(
      name: "Poseidon2Verifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Poseidon2Verifier>;
    getContractAt(
      name: "SmallerThan",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmallerThan>;
    getContractAt(
      name: "TestVerifyAlwaysTrue",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TestVerifyAlwaysTrue>;
    getContractAt(
      name: "TimeDelayProof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TimeDelayProof>;
    getContractAt(
      name: "TopLevelMerkleProof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TopLevelMerkleProof>;
    getContractAt(
      name: "ValueInjection",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ValueInjection>;
    getContractAt(
      name: "VerifyECDSA",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VerifyECDSA>;
    getContractAt(
      name: "VerifyEDDSA",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VerifyEDDSA>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "Strings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "ChainedProof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ChainedProof>;
    deployContract(
      name: "HashFunction",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HashFunction>;
    deployContract(
      name: "ChainedProofV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ChainedProofV2>;
    deployContract(
      name: "HashFunctionV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HashFunctionV2>;
    deployContract(
      name: "EmpheralDualMerkleTreeKeccak",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmpheralDualMerkleTreeKeccak>;
    deployContract(
      name: "EmpheralMerkleTreeKeccak",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmpheralMerkleTreeKeccak>;
    deployContract(
      name: "IDataStream",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDataStream>;
    deployContract(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "NihiliumRecoveryRegister",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NihiliumRecoveryRegister>;
    deployContract(
      name: "AdditionProof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AdditionProof>;
    deployContract(
      name: "Between",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Between>;
    deployContract(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "Email_send_no_body",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Email_send_no_body>;
    deployContract(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "BaseHonkVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "Encrypt_proof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Encrypt_proof>;
    deployContract(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "GreaterOrEqualThen",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GreaterOrEqualThen>;
    deployContract(
      name: "Hash_tie",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Hash_tie>;
    deployContract(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "KeccakPreImage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.KeccakPreImage>;
    deployContract(
      name: "KeccakTreeEntry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.KeccakTreeEntry>;
    deployContract(
      name: "ManualChoice",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ManualChoice>;
    deployContract(
      name: "MerkleTreeProof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MerkleTreeProof>;
    deployContract(
      name: "Opening_proof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Opening_proof>;
    deployContract(
      name: "Poseidon2Verifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Poseidon2Verifier>;
    deployContract(
      name: "SmallerThan",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmallerThan>;
    deployContract(
      name: "TestVerifyAlwaysTrue",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestVerifyAlwaysTrue>;
    deployContract(
      name: "TimeDelayProof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TimeDelayProof>;
    deployContract(
      name: "TopLevelMerkleProof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TopLevelMerkleProof>;
    deployContract(
      name: "ValueInjection",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ValueInjection>;
    deployContract(
      name: "VerifyECDSA",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VerifyECDSA>;
    deployContract(
      name: "VerifyEDDSA",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VerifyEDDSA>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "SafeCast",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "Strings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "ChainedProof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ChainedProof>;
    deployContract(
      name: "HashFunction",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HashFunction>;
    deployContract(
      name: "ChainedProofV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ChainedProofV2>;
    deployContract(
      name: "HashFunctionV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HashFunctionV2>;
    deployContract(
      name: "EmpheralDualMerkleTreeKeccak",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmpheralDualMerkleTreeKeccak>;
    deployContract(
      name: "EmpheralMerkleTreeKeccak",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmpheralMerkleTreeKeccak>;
    deployContract(
      name: "IDataStream",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDataStream>;
    deployContract(
      name: "IVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "NihiliumRecoveryRegister",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NihiliumRecoveryRegister>;
    deployContract(
      name: "AdditionProof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AdditionProof>;
    deployContract(
      name: "Between",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Between>;
    deployContract(
      name: "BaseHonkVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "Email_send_no_body",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Email_send_no_body>;
    deployContract(
      name: "IVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "BaseHonkVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseHonkVerifier>;
    deployContract(
      name: "Encrypt_proof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Encrypt_proof>;
    deployContract(
      name: "IVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "GreaterOrEqualThen",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GreaterOrEqualThen>;
    deployContract(
      name: "Hash_tie",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Hash_tie>;
    deployContract(
      name: "IVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "KeccakPreImage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.KeccakPreImage>;
    deployContract(
      name: "KeccakTreeEntry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.KeccakTreeEntry>;
    deployContract(
      name: "ManualChoice",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ManualChoice>;
    deployContract(
      name: "MerkleTreeProof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MerkleTreeProof>;
    deployContract(
      name: "Opening_proof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Opening_proof>;
    deployContract(
      name: "Poseidon2Verifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Poseidon2Verifier>;
    deployContract(
      name: "SmallerThan",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmallerThan>;
    deployContract(
      name: "TestVerifyAlwaysTrue",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestVerifyAlwaysTrue>;
    deployContract(
      name: "TimeDelayProof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TimeDelayProof>;
    deployContract(
      name: "TopLevelMerkleProof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TopLevelMerkleProof>;
    deployContract(
      name: "ValueInjection",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ValueInjection>;
    deployContract(
      name: "VerifyECDSA",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VerifyECDSA>;
    deployContract(
      name: "VerifyEDDSA",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VerifyEDDSA>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
