/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  SmallerThen,
  SmallerThenInterface,
} from "../../../contracts/proofs/SmallerThen";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "publicSignals",
        type: "bytes32[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506101e38061001f6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063ea50d0e414610030575b600080fd5b61004361003e3660046100ae565b610057565b604051901515815260200160405180910390f35b60006002821461006957610069610181565b8282600181811061007c5761007c610197565b9050602002013560001c8383600081811061009957610099610197565b9050602002013560001c109050949350505050565b600080600080604085870312156100c457600080fd5b843567ffffffffffffffff8111156100db57600080fd5b8501601f810187136100ec57600080fd5b803567ffffffffffffffff81111561010357600080fd5b87602082840101111561011557600080fd5b60209182019550935085013567ffffffffffffffff81111561013657600080fd5b8501601f8101871361014757600080fd5b803567ffffffffffffffff81111561015e57600080fd5b8760208260051b840101111561017357600080fd5b949793965060200194505050565b634e487b7160e01b600052600160045260246000fd5b634e487b7160e01b600052603260045260246000fdfea2646970667358221220c6cec920aa64ea54de6d4dec88ba5f6ec0eab9d2a6a9830aa3b0a99bfb6f4d0d64736f6c634300081b0033";

type SmallerThenConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SmallerThenConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SmallerThen__factory extends ContractFactory {
  constructor(...args: SmallerThenConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SmallerThen & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SmallerThen__factory {
    return super.connect(runner) as SmallerThen__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SmallerThenInterface {
    return new Interface(_abi) as SmallerThenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): SmallerThen {
    return new Contract(address, _abi, runner) as unknown as SmallerThen;
  }
}
