/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  SmallerThan,
  SmallerThanInterface,
} from "../../../contracts/proofs/SmallerThan";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "publicSignals",
        type: "bytes32[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b506101cd8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610029575f3560e01c8063ea50d0e41461002d575b5f5ffd5b61004061003b3660046100a7565b610054565b604051901515815260200160405180910390f35b5f600282146100655761006561016f565b8282600181811061007857610078610183565b905060200201355f1c83835f81811061009357610093610183565b905060200201355f1c109050949350505050565b5f5f5f5f604085870312156100ba575f5ffd5b843567ffffffffffffffff8111156100d0575f5ffd5b8501601f810187136100e0575f5ffd5b803567ffffffffffffffff8111156100f6575f5ffd5b876020828401011115610107575f5ffd5b60209182019550935085013567ffffffffffffffff811115610127575f5ffd5b8501601f81018713610137575f5ffd5b803567ffffffffffffffff81111561014d575f5ffd5b8760208260051b8401011115610161575f5ffd5b949793965060200194505050565b634e487b7160e01b5f52600160045260245ffd5b634e487b7160e01b5f52603260045260245ffdfea2646970667358221220d13371a862db8aafe049dde0cff900e8d286cbd462498edaed9aa4111e5a12b464736f6c634300081b0033";

type SmallerThanConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SmallerThanConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SmallerThan__factory extends ContractFactory {
  constructor(...args: SmallerThanConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SmallerThan & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SmallerThan__factory {
    return super.connect(runner) as SmallerThan__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SmallerThanInterface {
    return new Interface(_abi) as SmallerThanInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): SmallerThan {
    return new Contract(address, _abi, runner) as unknown as SmallerThan;
  }
}
