/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  TimeBetweenProof,
  TimeBetweenProofInterface,
} from "../../../contracts/proofs/TimeBetweenProof";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "publicSignals",
        type: "bytes32[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506102258061001f6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063ea50d0e414610030575b600080fd5b61004361003e3660046100f0565b610057565b604051901515815260200160405180910390f35b600060038214610069576100696101c3565b8282600181811061007c5761007c6101d9565b9050602002013560001c83836000818110610099576100996101d9565b9050602002013560001c1180156100e75750828260028181106100be576100be6101d9565b9050602002013560001c838360008181106100db576100db6101d9565b9050602002013560001c105b95945050505050565b6000806000806040858703121561010657600080fd5b843567ffffffffffffffff81111561011d57600080fd5b8501601f8101871361012e57600080fd5b803567ffffffffffffffff81111561014557600080fd5b87602082840101111561015757600080fd5b60209182019550935085013567ffffffffffffffff81111561017857600080fd5b8501601f8101871361018957600080fd5b803567ffffffffffffffff8111156101a057600080fd5b8760208260051b84010111156101b557600080fd5b949793965060200194505050565b634e487b7160e01b600052600160045260246000fd5b634e487b7160e01b600052603260045260246000fdfea2646970667358221220e29ff30aca1e4b11721e116d0b538867d23ece238bfb57cf06384f586820513a64736f6c634300081b0033";

type TimeBetweenProofConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TimeBetweenProofConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TimeBetweenProof__factory extends ContractFactory {
  constructor(...args: TimeBetweenProofConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TimeBetweenProof & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TimeBetweenProof__factory {
    return super.connect(runner) as TimeBetweenProof__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TimeBetweenProofInterface {
    return new Interface(_abi) as TimeBetweenProofInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TimeBetweenProof {
    return new Contract(address, _abi, runner) as unknown as TimeBetweenProof;
  }
}
