/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type ProvingStateV2Struct = {
  current_hash: BytesLike;
  current_index: BigNumberish;
  outputs: BytesLike[];
  prepared_public_inputs: BytesLike[];
  prepared_proof: BytesLike;
  verifier_must_be_true: boolean;
  proof_verifier: AddressLike;
  initiator: AddressLike;
};

export type ProvingStateV2StructOutput = [
  current_hash: string,
  current_index: bigint,
  outputs: string[],
  prepared_public_inputs: string[],
  prepared_proof: string,
  verifier_must_be_true: boolean,
  proof_verifier: string,
  initiator: string
] & {
  current_hash: string;
  current_index: bigint;
  outputs: string[];
  prepared_public_inputs: string[];
  prepared_proof: string;
  verifier_must_be_true: boolean;
  proof_verifier: string;
  initiator: string;
};

export interface ChainedProofV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "_dryrun_chain_pass_signal"
      | "_dryrun_chain_proof_verify"
      | "_dryrun_chain_static_input"
      | "_dryrun_prepare_next_proof"
      | "_dryrun_validate_data_root"
      | "dryrun_chain_pass_signal"
      | "dryrun_chain_proof_verify"
      | "dryrun_chain_static_input"
      | "dryrun_prepare_next_proof"
      | "dryrun_validate_data_root"
      | "forced_opening_verifier"
      | "has_data_stream_root"
      | "hashProvingState"
      | "provingStates"
      | "public_proof_verifier"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_dryrun_chain_pass_signal",
    values: [
      ProvingStateV2Struct,
      [BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "_dryrun_chain_proof_verify",
    values: [ProvingStateV2Struct, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "_dryrun_chain_static_input",
    values: [ProvingStateV2Struct, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_dryrun_prepare_next_proof",
    values: [ProvingStateV2Struct, AddressLike, boolean, BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "_dryrun_validate_data_root",
    values: [ProvingStateV2Struct, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dryrun_chain_pass_signal",
    values: [
      ProvingStateV2Struct,
      [BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "dryrun_chain_proof_verify",
    values: [ProvingStateV2Struct, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "dryrun_chain_static_input",
    values: [ProvingStateV2Struct, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dryrun_prepare_next_proof",
    values: [ProvingStateV2Struct, AddressLike, boolean, BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dryrun_validate_data_root",
    values: [ProvingStateV2Struct, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forced_opening_verifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "has_data_stream_root",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashProvingState",
    values: [ProvingStateV2Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "provingStates",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "public_proof_verifier",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "_dryrun_chain_pass_signal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_dryrun_chain_proof_verify",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_dryrun_chain_static_input",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_dryrun_prepare_next_proof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_dryrun_validate_data_root",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dryrun_chain_pass_signal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dryrun_chain_proof_verify",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dryrun_chain_static_input",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dryrun_prepare_next_proof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dryrun_validate_data_root",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forced_opening_verifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "has_data_stream_root",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashProvingState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "provingStates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "public_proof_verifier",
    data: BytesLike
  ): Result;
}

export interface ChainedProofV2 extends BaseContract {
  connect(runner?: ContractRunner | null): ChainedProofV2;
  waitForDeployment(): Promise<this>;

  interface: ChainedProofV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _dryrun_chain_pass_signal: TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      public_input_indexes: [BigNumberish, BigNumberish],
      output_indexes: [BigNumberish, BigNumberish]
    ],
    [ProvingStateV2StructOutput],
    "view"
  >;

  _dryrun_chain_proof_verify: TypedContractMethod<
    [state: ProvingStateV2Struct, mask: BigNumberish, ignore_proof: boolean],
    [ProvingStateV2StructOutput],
    "view"
  >;

  _dryrun_chain_static_input: TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      value: BytesLike,
      public_input_index: BigNumberish
    ],
    [ProvingStateV2StructOutput],
    "view"
  >;

  _dryrun_prepare_next_proof: TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      _verifier: AddressLike,
      _verifierMustBeTrue: boolean,
      _publicInputs: BytesLike[],
      _proof: BytesLike
    ],
    [ProvingStateV2StructOutput],
    "view"
  >;

  _dryrun_validate_data_root: TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      datastream: AddressLike,
      output_signal_index: BigNumberish
    ],
    [ProvingStateV2StructOutput],
    "view"
  >;

  dryrun_chain_pass_signal: TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      public_input_indexes: [BigNumberish, BigNumberish],
      output_indexes: [BigNumberish, BigNumberish]
    ],
    [string],
    "view"
  >;

  dryrun_chain_proof_verify: TypedContractMethod<
    [state: ProvingStateV2Struct, mask: BigNumberish, ignore_proof: boolean],
    [string],
    "view"
  >;

  dryrun_chain_static_input: TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      value: BytesLike,
      public_input_index: BigNumberish
    ],
    [string],
    "view"
  >;

  dryrun_prepare_next_proof: TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      _verifier: AddressLike,
      _verifierMustBeTrue: boolean,
      _publicInputs: BytesLike[],
      _proof: BytesLike
    ],
    [string],
    "view"
  >;

  dryrun_validate_data_root: TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      datastream: AddressLike,
      output_signal_index: BigNumberish
    ],
    [string],
    "view"
  >;

  forced_opening_verifier: TypedContractMethod<[], [string], "view">;

  has_data_stream_root: TypedContractMethod<
    [_datastream: AddressLike, _root: BytesLike],
    [boolean],
    "view"
  >;

  hashProvingState: TypedContractMethod<
    [state: ProvingStateV2Struct],
    [string],
    "view"
  >;

  provingStates: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, boolean, string, string] & {
        current_hash: string;
        current_index: bigint;
        prepared_proof: string;
        verifier_must_be_true: boolean;
        proof_verifier: string;
        initiator: string;
      }
    ],
    "view"
  >;

  public_proof_verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_dryrun_chain_pass_signal"
  ): TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      public_input_indexes: [BigNumberish, BigNumberish],
      output_indexes: [BigNumberish, BigNumberish]
    ],
    [ProvingStateV2StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "_dryrun_chain_proof_verify"
  ): TypedContractMethod<
    [state: ProvingStateV2Struct, mask: BigNumberish, ignore_proof: boolean],
    [ProvingStateV2StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "_dryrun_chain_static_input"
  ): TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      value: BytesLike,
      public_input_index: BigNumberish
    ],
    [ProvingStateV2StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "_dryrun_prepare_next_proof"
  ): TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      _verifier: AddressLike,
      _verifierMustBeTrue: boolean,
      _publicInputs: BytesLike[],
      _proof: BytesLike
    ],
    [ProvingStateV2StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "_dryrun_validate_data_root"
  ): TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      datastream: AddressLike,
      output_signal_index: BigNumberish
    ],
    [ProvingStateV2StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "dryrun_chain_pass_signal"
  ): TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      public_input_indexes: [BigNumberish, BigNumberish],
      output_indexes: [BigNumberish, BigNumberish]
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "dryrun_chain_proof_verify"
  ): TypedContractMethod<
    [state: ProvingStateV2Struct, mask: BigNumberish, ignore_proof: boolean],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "dryrun_chain_static_input"
  ): TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      value: BytesLike,
      public_input_index: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "dryrun_prepare_next_proof"
  ): TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      _verifier: AddressLike,
      _verifierMustBeTrue: boolean,
      _publicInputs: BytesLike[],
      _proof: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "dryrun_validate_data_root"
  ): TypedContractMethod<
    [
      state: ProvingStateV2Struct,
      datastream: AddressLike,
      output_signal_index: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "forced_opening_verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "has_data_stream_root"
  ): TypedContractMethod<
    [_datastream: AddressLike, _root: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashProvingState"
  ): TypedContractMethod<[state: ProvingStateV2Struct], [string], "view">;
  getFunction(
    nameOrSignature: "provingStates"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, boolean, string, string] & {
        current_hash: string;
        current_index: bigint;
        prepared_proof: string;
        verifier_must_be_true: boolean;
        proof_verifier: string;
        initiator: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "public_proof_verifier"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
