/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  DynamicCallProxyProof,
  DynamicCallProxyProofInterface,
} from "../../../../contracts/proofs/FixedCallProxy.sol/DynamicCallProxyProof";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "publicSignals",
        type: "bytes32[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b506102be8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610029575f3560e01c8063ea50d0e41461002d575b5f5ffd5b61004061003b3660046100f9565b610054565b604051901515815260200160405180910390f35b5f5f83835f818110610068576100686101c1565b60200291909101359150506001600160a01b03811663ea50d0e48787610091876001818b6101d5565b6040518563ffffffff1660e01b81526004016100b09493929190610200565b602060405180830381865afa1580156100cb573d5f5f3e3d5ffd5b505050506040513d601f19601f820116820180604052508101906100ef9190610262565b9695505050505050565b5f5f5f5f6040858703121561010c575f5ffd5b843567ffffffffffffffff811115610122575f5ffd5b8501601f81018713610132575f5ffd5b803567ffffffffffffffff811115610148575f5ffd5b876020828401011115610159575f5ffd5b60209182019550935085013567ffffffffffffffff811115610179575f5ffd5b8501601f81018713610189575f5ffd5b803567ffffffffffffffff81111561019f575f5ffd5b8760208260051b84010111156101b3575f5ffd5b949793965060200194505050565b634e487b7160e01b5f52603260045260245ffd5b5f5f858511156101e3575f5ffd5b838611156101ef575f5ffd5b5050600583901b0193919092039150565b60408152836040820152838560608301375f60608583018101829052601f19601f8701168301838103820160208501529081018490526001600160fb1b03841115610249575f5ffd5b8360051b80866080840137016080019695505050505050565b5f60208284031215610272575f5ffd5b81518015158114610281575f5ffd5b939250505056fea2646970667358221220eeef6cea56c153f6d3f7649f67af298987bd1c25a44cfaada1336069922b5b1c64736f6c634300081b0033";

type DynamicCallProxyProofConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DynamicCallProxyProofConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DynamicCallProxyProof__factory extends ContractFactory {
  constructor(...args: DynamicCallProxyProofConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      DynamicCallProxyProof & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): DynamicCallProxyProof__factory {
    return super.connect(runner) as DynamicCallProxyProof__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DynamicCallProxyProofInterface {
    return new Interface(_abi) as DynamicCallProxyProofInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): DynamicCallProxyProof {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as DynamicCallProxyProof;
  }
}
