/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  FixedCallProxyProof,
  FixedCallProxyProofInterface,
} from "../../../../contracts/proofs/FixedCallProxy.sol/FixedCallProxyProof";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "publicSignals",
        type: "bytes32[]",
      },
    ],
    name: "internal_verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "isContract",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_proof",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "_publicInputs",
        type: "bytes32[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class FixedCallProxyProof__factory {
  static readonly abi = _abi;
  static createInterface(): FixedCallProxyProofInterface {
    return new Interface(_abi) as FixedCallProxyProofInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): FixedCallProxyProof {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as FixedCallProxyProof;
  }
}
