/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IZKPassportRootVerifier } from "./IZKPassportRootVerifier";
export type { ZKPassportProof } from "./ZKPassportProof";
