/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DKIMRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "NOT_REVOKED"
      | "addKeyOperationId"
      | "cancelOperation"
      | "computeSignedMsg"
      | "executeAddKey"
      | "executeSetOracleSigner"
      | "executeSetTimelockPeriod"
      | "isKeyHashValidAt"
      | "isOperationReady"
      | "oracleSigner"
      | "owner"
      | "revokeDKIMPublicKeyHash"
      | "revokedAt"
      | "scheduleAddKey"
      | "scheduleSetOracleSigner"
      | "scheduleSetTimelockPeriod"
      | "scheduledAt"
      | "setDKIMPublicKeyHash"
      | "setOracleSignerOperationId"
      | "setTimelockPeriodOperationId"
      | "timelockPeriod"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DKIMPublicKeyHashRegistered"
      | "DKIMPublicKeyHashRevoked"
      | "OperationCancelled"
      | "OperationExecuted"
      | "OperationScheduled"
      | "OracleSignerChanged"
      | "OwnershipTransferred"
      | "TimelockPeriodChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "NOT_REVOKED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addKeyOperationId",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOperation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "computeSignedMsg",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeAddKey",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSetOracleSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSetTimelockPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isKeyHashValidAt",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperationReady",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleSigner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeDKIMPublicKeyHash",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokedAt",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleAddKey",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleSetOracleSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleSetTimelockPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduledAt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDKIMPublicKeyHash",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracleSignerOperationId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimelockPeriodOperationId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "timelockPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "NOT_REVOKED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addKeyOperationId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeSignedMsg",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeAddKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSetOracleSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSetTimelockPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isKeyHashValidAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperationReady",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeDKIMPublicKeyHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokedAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "scheduleAddKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleSetOracleSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleSetTimelockPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduledAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDKIMPublicKeyHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOracleSignerOperationId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimelockPeriodOperationId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timelockPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DKIMPublicKeyHashRegisteredEvent {
  export type InputTuple = [
    domainNameHash: BytesLike,
    publicKeyHash: BytesLike
  ];
  export type OutputTuple = [domainNameHash: string, publicKeyHash: string];
  export interface OutputObject {
    domainNameHash: string;
    publicKeyHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DKIMPublicKeyHashRevokedEvent {
  export type InputTuple = [
    domainNameHash: BytesLike,
    publicKeyHash: BytesLike,
    revokedAt: BigNumberish
  ];
  export type OutputTuple = [
    domainNameHash: string,
    publicKeyHash: string,
    revokedAt: bigint
  ];
  export interface OutputObject {
    domainNameHash: string;
    publicKeyHash: string;
    revokedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperationCancelledEvent {
  export type InputTuple = [operationId: BytesLike];
  export type OutputTuple = [operationId: string];
  export interface OutputObject {
    operationId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperationExecutedEvent {
  export type InputTuple = [operationId: BytesLike];
  export type OutputTuple = [operationId: string];
  export interface OutputObject {
    operationId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperationScheduledEvent {
  export type InputTuple = [operationId: BytesLike, readyAt: BigNumberish];
  export type OutputTuple = [operationId: string, readyAt: bigint];
  export interface OutputObject {
    operationId: string;
    readyAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleSignerChangedEvent {
  export type InputTuple = [
    previousSigner: AddressLike,
    newSigner: AddressLike
  ];
  export type OutputTuple = [previousSigner: string, newSigner: string];
  export interface OutputObject {
    previousSigner: string;
    newSigner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockPeriodChangedEvent {
  export type InputTuple = [
    previousPeriod: BigNumberish,
    newPeriod: BigNumberish
  ];
  export type OutputTuple = [previousPeriod: bigint, newPeriod: bigint];
  export interface OutputObject {
    previousPeriod: bigint;
    newPeriod: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DKIMRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DKIMRegistry;
  waitForDeployment(): Promise<this>;

  interface: DKIMRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  NOT_REVOKED: TypedContractMethod<[], [bigint], "view">;

  addKeyOperationId: TypedContractMethod<
    [domainName: string, publicKeyHash: BytesLike],
    [string],
    "view"
  >;

  cancelOperation: TypedContractMethod<
    [operationId: BytesLike],
    [void],
    "nonpayable"
  >;

  computeSignedMsg: TypedContractMethod<
    [domainName: string, publicKeyHash: BytesLike],
    [string],
    "view"
  >;

  executeAddKey: TypedContractMethod<
    [domainName: string, publicKeyHash: BytesLike],
    [void],
    "nonpayable"
  >;

  executeSetOracleSigner: TypedContractMethod<
    [newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  executeSetTimelockPeriod: TypedContractMethod<
    [newPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  isKeyHashValidAt: TypedContractMethod<
    [
      domainNameHash: BytesLike,
      publicKeyHash: BytesLike,
      timestamp: BigNumberish
    ],
    [boolean],
    "view"
  >;

  isOperationReady: TypedContractMethod<
    [operationId: BytesLike],
    [boolean],
    "view"
  >;

  oracleSigner: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  revokeDKIMPublicKeyHash: TypedContractMethod<
    [domainNameHash: BytesLike, publicKeyHash: BytesLike],
    [void],
    "nonpayable"
  >;

  revokedAt: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [bigint],
    "view"
  >;

  scheduleAddKey: TypedContractMethod<
    [domainName: string, publicKeyHash: BytesLike],
    [void],
    "nonpayable"
  >;

  scheduleSetOracleSigner: TypedContractMethod<
    [newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  scheduleSetTimelockPeriod: TypedContractMethod<
    [newPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  scheduledAt: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  setDKIMPublicKeyHash: TypedContractMethod<
    [domainName: string, publicKeyHash: BytesLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  setOracleSignerOperationId: TypedContractMethod<
    [newSigner: AddressLike],
    [string],
    "view"
  >;

  setTimelockPeriodOperationId: TypedContractMethod<
    [newPeriod: BigNumberish],
    [string],
    "view"
  >;

  timelockPeriod: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "NOT_REVOKED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addKeyOperationId"
  ): TypedContractMethod<
    [domainName: string, publicKeyHash: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelOperation"
  ): TypedContractMethod<[operationId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "computeSignedMsg"
  ): TypedContractMethod<
    [domainName: string, publicKeyHash: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeAddKey"
  ): TypedContractMethod<
    [domainName: string, publicKeyHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeSetOracleSigner"
  ): TypedContractMethod<[newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeSetTimelockPeriod"
  ): TypedContractMethod<[newPeriod: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isKeyHashValidAt"
  ): TypedContractMethod<
    [
      domainNameHash: BytesLike,
      publicKeyHash: BytesLike,
      timestamp: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOperationReady"
  ): TypedContractMethod<[operationId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "oracleSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeDKIMPublicKeyHash"
  ): TypedContractMethod<
    [domainNameHash: BytesLike, publicKeyHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokedAt"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "scheduleAddKey"
  ): TypedContractMethod<
    [domainName: string, publicKeyHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scheduleSetOracleSigner"
  ): TypedContractMethod<[newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scheduleSetTimelockPeriod"
  ): TypedContractMethod<[newPeriod: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scheduledAt"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setDKIMPublicKeyHash"
  ): TypedContractMethod<
    [domainName: string, publicKeyHash: BytesLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOracleSignerOperationId"
  ): TypedContractMethod<[newSigner: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "setTimelockPeriodOperationId"
  ): TypedContractMethod<[newPeriod: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "timelockPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DKIMPublicKeyHashRegistered"
  ): TypedContractEvent<
    DKIMPublicKeyHashRegisteredEvent.InputTuple,
    DKIMPublicKeyHashRegisteredEvent.OutputTuple,
    DKIMPublicKeyHashRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DKIMPublicKeyHashRevoked"
  ): TypedContractEvent<
    DKIMPublicKeyHashRevokedEvent.InputTuple,
    DKIMPublicKeyHashRevokedEvent.OutputTuple,
    DKIMPublicKeyHashRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OperationCancelled"
  ): TypedContractEvent<
    OperationCancelledEvent.InputTuple,
    OperationCancelledEvent.OutputTuple,
    OperationCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OperationExecuted"
  ): TypedContractEvent<
    OperationExecutedEvent.InputTuple,
    OperationExecutedEvent.OutputTuple,
    OperationExecutedEvent.OutputObject
  >;
  getEvent(
    key: "OperationScheduled"
  ): TypedContractEvent<
    OperationScheduledEvent.InputTuple,
    OperationScheduledEvent.OutputTuple,
    OperationScheduledEvent.OutputObject
  >;
  getEvent(
    key: "OracleSignerChanged"
  ): TypedContractEvent<
    OracleSignerChangedEvent.InputTuple,
    OracleSignerChangedEvent.OutputTuple,
    OracleSignerChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TimelockPeriodChanged"
  ): TypedContractEvent<
    TimelockPeriodChangedEvent.InputTuple,
    TimelockPeriodChangedEvent.OutputTuple,
    TimelockPeriodChangedEvent.OutputObject
  >;

  filters: {
    "DKIMPublicKeyHashRegistered(bytes32,bytes32)": TypedContractEvent<
      DKIMPublicKeyHashRegisteredEvent.InputTuple,
      DKIMPublicKeyHashRegisteredEvent.OutputTuple,
      DKIMPublicKeyHashRegisteredEvent.OutputObject
    >;
    DKIMPublicKeyHashRegistered: TypedContractEvent<
      DKIMPublicKeyHashRegisteredEvent.InputTuple,
      DKIMPublicKeyHashRegisteredEvent.OutputTuple,
      DKIMPublicKeyHashRegisteredEvent.OutputObject
    >;

    "DKIMPublicKeyHashRevoked(bytes32,bytes32,uint256)": TypedContractEvent<
      DKIMPublicKeyHashRevokedEvent.InputTuple,
      DKIMPublicKeyHashRevokedEvent.OutputTuple,
      DKIMPublicKeyHashRevokedEvent.OutputObject
    >;
    DKIMPublicKeyHashRevoked: TypedContractEvent<
      DKIMPublicKeyHashRevokedEvent.InputTuple,
      DKIMPublicKeyHashRevokedEvent.OutputTuple,
      DKIMPublicKeyHashRevokedEvent.OutputObject
    >;

    "OperationCancelled(bytes32)": TypedContractEvent<
      OperationCancelledEvent.InputTuple,
      OperationCancelledEvent.OutputTuple,
      OperationCancelledEvent.OutputObject
    >;
    OperationCancelled: TypedContractEvent<
      OperationCancelledEvent.InputTuple,
      OperationCancelledEvent.OutputTuple,
      OperationCancelledEvent.OutputObject
    >;

    "OperationExecuted(bytes32)": TypedContractEvent<
      OperationExecutedEvent.InputTuple,
      OperationExecutedEvent.OutputTuple,
      OperationExecutedEvent.OutputObject
    >;
    OperationExecuted: TypedContractEvent<
      OperationExecutedEvent.InputTuple,
      OperationExecutedEvent.OutputTuple,
      OperationExecutedEvent.OutputObject
    >;

    "OperationScheduled(bytes32,uint256)": TypedContractEvent<
      OperationScheduledEvent.InputTuple,
      OperationScheduledEvent.OutputTuple,
      OperationScheduledEvent.OutputObject
    >;
    OperationScheduled: TypedContractEvent<
      OperationScheduledEvent.InputTuple,
      OperationScheduledEvent.OutputTuple,
      OperationScheduledEvent.OutputObject
    >;

    "OracleSignerChanged(address,address)": TypedContractEvent<
      OracleSignerChangedEvent.InputTuple,
      OracleSignerChangedEvent.OutputTuple,
      OracleSignerChangedEvent.OutputObject
    >;
    OracleSignerChanged: TypedContractEvent<
      OracleSignerChangedEvent.InputTuple,
      OracleSignerChangedEvent.OutputTuple,
      OracleSignerChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TimelockPeriodChanged(uint256,uint256)": TypedContractEvent<
      TimelockPeriodChangedEvent.InputTuple,
      TimelockPeriodChangedEvent.OutputTuple,
      TimelockPeriodChangedEvent.OutputObject
    >;
    TimelockPeriodChanged: TypedContractEvent<
      TimelockPeriodChangedEvent.InputTuple,
      TimelockPeriodChangedEvent.OutputTuple,
      TimelockPeriodChangedEvent.OutputObject
    >;
  };
}
