/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FormatBoundDataInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BOUND_DATA_IDENTIFIER_CUSTOM_DATA"
      | "MAX_DATA_LENGTH"
      | "MAX_FIELD_SIZE"
      | "PROOF_TYPE_BIND"
      | "PROOF_TYPE_LENGTH_BIND_EVM"
      | "bytes32ToHexString"
      | "computeSha256"
      | "formatBytes32Data"
      | "formatCustomData"
      | "formatCustomDataAsUint8Array"
      | "getBindEVMParameterCommitment(bytes)"
      | "getBindEVMParameterCommitment(bytes,uint256)"
      | "numberToBytesBE"
      | "packBeBytesIntoField"
      | "rightPadArrayWithZeros"
      | "verify"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BOUND_DATA_IDENTIFIER_CUSTOM_DATA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DATA_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FIELD_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROOF_TYPE_BIND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROOF_TYPE_LENGTH_BIND_EVM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bytes32ToHexString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "computeSha256",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "formatBytes32Data",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "formatCustomData",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "formatCustomDataAsUint8Array",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBindEVMParameterCommitment(bytes)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBindEVMParameterCommitment(bytes,uint256)",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "numberToBytesBE",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "packBeBytesIntoField",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rightPadArrayWithZeros",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "BOUND_DATA_IDENTIFIER_CUSTOM_DATA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DATA_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FIELD_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROOF_TYPE_BIND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROOF_TYPE_LENGTH_BIND_EVM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bytes32ToHexString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeSha256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "formatBytes32Data",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "formatCustomData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "formatCustomDataAsUint8Array",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBindEVMParameterCommitment(bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBindEVMParameterCommitment(bytes,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberToBytesBE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "packBeBytesIntoField",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rightPadArrayWithZeros",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export interface FormatBoundData extends BaseContract {
  connect(runner?: ContractRunner | null): FormatBoundData;
  waitForDeployment(): Promise<this>;

  interface: FormatBoundDataInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BOUND_DATA_IDENTIFIER_CUSTOM_DATA: TypedContractMethod<[], [bigint], "view">;

  MAX_DATA_LENGTH: TypedContractMethod<[], [bigint], "view">;

  MAX_FIELD_SIZE: TypedContractMethod<[], [bigint], "view">;

  PROOF_TYPE_BIND: TypedContractMethod<[], [bigint], "view">;

  PROOF_TYPE_LENGTH_BIND_EVM: TypedContractMethod<[], [bigint], "view">;

  bytes32ToHexString: TypedContractMethod<[data: BytesLike], [string], "view">;

  computeSha256: TypedContractMethod<[data: BytesLike], [string], "view">;

  formatBytes32Data: TypedContractMethod<[data: BytesLike], [string], "view">;

  formatCustomData: TypedContractMethod<[customData: string], [string], "view">;

  formatCustomDataAsUint8Array: TypedContractMethod<
    [customData: string],
    [bigint[]],
    "view"
  >;

  "getBindEVMParameterCommitment(bytes)": TypedContractMethod<
    [data: BytesLike],
    [bigint],
    "view"
  >;

  "getBindEVMParameterCommitment(bytes,uint256)": TypedContractMethod<
    [data: BytesLike, maxLength: BigNumberish],
    [bigint],
    "view"
  >;

  numberToBytesBE: TypedContractMethod<
    [n: BigNumberish, len: BigNumberish],
    [string],
    "view"
  >;

  packBeBytesIntoField: TypedContractMethod<
    [x: BytesLike, maxFieldSize: BigNumberish],
    [bigint],
    "view"
  >;

  rightPadArrayWithZeros: TypedContractMethod<
    [data: BytesLike, maxLength: BigNumberish],
    [string],
    "view"
  >;

  verify: TypedContractMethod<
    [arg0: BytesLike, _publicInputs: BytesLike[]],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BOUND_DATA_IDENTIFIER_CUSTOM_DATA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DATA_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_FIELD_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROOF_TYPE_BIND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROOF_TYPE_LENGTH_BIND_EVM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bytes32ToHexString"
  ): TypedContractMethod<[data: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "computeSha256"
  ): TypedContractMethod<[data: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "formatBytes32Data"
  ): TypedContractMethod<[data: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "formatCustomData"
  ): TypedContractMethod<[customData: string], [string], "view">;
  getFunction(
    nameOrSignature: "formatCustomDataAsUint8Array"
  ): TypedContractMethod<[customData: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getBindEVMParameterCommitment(bytes)"
  ): TypedContractMethod<[data: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBindEVMParameterCommitment(bytes,uint256)"
  ): TypedContractMethod<
    [data: BytesLike, maxLength: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "numberToBytesBE"
  ): TypedContractMethod<
    [n: BigNumberish, len: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "packBeBytesIntoField"
  ): TypedContractMethod<
    [x: BytesLike, maxFieldSize: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "rightPadArrayWithZeros"
  ): TypedContractMethod<
    [data: BytesLike, maxLength: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [arg0: BytesLike, _publicInputs: BytesLike[]],
    [boolean],
    "view"
  >;

  filters: {};
}
