/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SubTreeMerkleProofInterface extends Interface {
  getFunction(
    nameOrSignature: "_efficientHash" | "extractBytes32List" | "verify"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Log"): EventFragment;

  encodeFunctionData(
    functionFragment: "_efficientHash",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "extractBytes32List",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "_efficientHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extractBytes32List",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace LogEvent {
  export type InputTuple = [v1: BytesLike, v2: BytesLike, v3: BytesLike];
  export type OutputTuple = [v1: string, v2: string, v3: string];
  export interface OutputObject {
    v1: string;
    v2: string;
    v3: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SubTreeMerkleProof extends BaseContract {
  connect(runner?: ContractRunner | null): SubTreeMerkleProof;
  waitForDeployment(): Promise<this>;

  interface: SubTreeMerkleProofInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _efficientHash: TypedContractMethod<
    [a: BytesLike, b: BytesLike],
    [string],
    "view"
  >;

  extractBytes32List: TypedContractMethod<
    [data: BytesLike],
    [string[]],
    "view"
  >;

  verify: TypedContractMethod<
    [proof: BytesLike, publicSignals: BytesLike[]],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_efficientHash"
  ): TypedContractMethod<[a: BytesLike, b: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "extractBytes32List"
  ): TypedContractMethod<[data: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [proof: BytesLike, publicSignals: BytesLike[]],
    [boolean],
    "view"
  >;

  getEvent(
    key: "Log"
  ): TypedContractEvent<
    LogEvent.InputTuple,
    LogEvent.OutputTuple,
    LogEvent.OutputObject
  >;

  filters: {
    "Log(bytes32,bytes32,bytes32)": TypedContractEvent<
      LogEvent.InputTuple,
      LogEvent.OutputTuple,
      LogEvent.OutputObject
    >;
    Log: TypedContractEvent<
      LogEvent.InputTuple,
      LogEvent.OutputTuple,
      LogEvent.OutputObject
    >;
  };
}
