/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  TestZKPassportRoot,
  TestZKPassportRootInterface,
} from "../../../../contracts/proofs/TestZKPassportUpstream.sol/TestZKPassportRoot";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "version",
        type: "bytes32",
      },
    ],
    name: "getSubVerifier",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "version",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "subVerifier",
        type: "address",
      },
    ],
    name: "setSubVerifier",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "subVerifiers",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b506101728061001c5f395ff3fe608060405234801561000f575f5ffd5b506004361061003f575f3560e01c806378f2ef251461004357806395b4ae7014610080578063f2649807146100c4575b5f5ffd5b61007e6100513660046100ec565b5f9182526020829052604090912080546001600160a01b0319166001600160a01b03909216919091179055565b005b6100a861008e366004610125565b5f602081905290815260409020546001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b6100a86100d2366004610125565b5f908152602081905260409020546001600160a01b031690565b5f5f604083850312156100fd575f5ffd5b8235915060208301356001600160a01b038116811461011a575f5ffd5b809150509250929050565b5f60208284031215610135575f5ffd5b503591905056fea2646970667358221220eb07be3a40a6e2cabf855423e08803957608f555cb6ce1057451ee54e14521aa64736f6c634300081b0033";

type TestZKPassportRootConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TestZKPassportRootConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TestZKPassportRoot__factory extends ContractFactory {
  constructor(...args: TestZKPassportRootConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TestZKPassportRoot & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TestZKPassportRoot__factory {
    return super.connect(runner) as TestZKPassportRoot__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestZKPassportRootInterface {
    return new Interface(_abi) as TestZKPassportRootInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TestZKPassportRoot {
    return new Contract(address, _abi, runner) as unknown as TestZKPassportRoot;
  }
}
