/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  TestZKPassportSubVerifier,
  TestZKPassportSubVerifierInterface,
} from "../../../../contracts/proofs/TestZKPassportUpstream.sol/TestZKPassportSubVerifier";

const _abi = [
  {
    stateMutability: "nonpayable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "entries",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "vkeyHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "verifier",
        type: "address",
      },
    ],
    name: "setVerifier",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b5061026f8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c8063267b692214610109578063a692b9ef1461014d575b5f36606060248214801561006d5750630f4707c760e11b61005860045f858761018a565b610061916101b1565b6001600160e01b031916145b6100b35760405162461bcd60e51b81526020600482015260136024820152723ab732bc3832b1ba32b21039b2b632b1ba37b960691b604482015260640160405180910390fd5b5f6100c1836004818761018a565b8101906100ce91906101e9565b5f90815260208181526040918290205482516001600160a01b0390911681830152825180820383018152908301909252815195500192505050f35b6101316101173660046101e9565b5f602081905290815260409020546001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b61018861015b366004610200565b5f9182526020829052604090912080546001600160a01b0319166001600160a01b03909216919091179055565b005b5f5f85851115610198575f5ffd5b838611156101a4575f5ffd5b5050820193919092039150565b80356001600160e01b031981169060048410156101e2576001600160e01b0319600485900360031b81901b82161691505b5092915050565b5f602082840312156101f9575f5ffd5b5035919050565b5f5f60408385031215610211575f5ffd5b8235915060208301356001600160a01b038116811461022e575f5ffd5b80915050925092905056fea2646970667358221220e45f8cca4c18faafa83c4e30aa22a517b2c9a69d29f31a0c3f54a801a1440c4b64736f6c634300081b0033";

type TestZKPassportSubVerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TestZKPassportSubVerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TestZKPassportSubVerifier__factory extends ContractFactory {
  constructor(...args: TestZKPassportSubVerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TestZKPassportSubVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): TestZKPassportSubVerifier__factory {
    return super.connect(runner) as TestZKPassportSubVerifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestZKPassportSubVerifierInterface {
    return new Interface(_abi) as TestZKPassportSubVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TestZKPassportSubVerifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as TestZKPassportSubVerifier;
  }
}
