/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  NihiliumRecoveryRegister,
  NihiliumRecoveryRegisterInterface,
} from "../../contracts/NihiliumRecoveryRegister";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "getRecoveryAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "recoveryAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_recoveryAddress",
        type: "address",
      },
    ],
    name: "registerRecovery",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b5060405161032d38038061032d833981016040819052602b9160b4565b806001600160a01b038116605857604051631e4fbdf760e01b81525f600482015260240160405180910390fd5b605f816065565b505060df565b5f80546001600160a01b038381166001600160a01b0319831681178455604051919092169283917f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e09190a35050565b5f6020828403121560c3575f5ffd5b81516001600160a01b038116811460d8575f5ffd5b9392505050565b610241806100ec5f395ff3fe608060405234801561000f575f5ffd5b5060043610610060575f3560e01c80632e583a9214610064578063710eb26c14610079578063715018a6146100a85780638c714b92146100b05780638da5cb5b146100c1578063f2fde38b146100d1575b5f5ffd5b6100776100723660046101de565b6100e4565b005b60015461008c906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b61007761010e565b6001546001600160a01b031661008c565b5f546001600160a01b031661008c565b6100776100df3660046101de565b610121565b6100ec610163565b600180546001600160a01b0319166001600160a01b0392909216919091179055565b610116610163565b61011f5f61018f565b565b610129610163565b6001600160a01b03811661015757604051631e4fbdf760e01b81525f60048201526024015b60405180910390fd5b6101608161018f565b50565b5f546001600160a01b0316331461011f5760405163118cdaa760e01b815233600482015260240161014e565b5f80546001600160a01b038381166001600160a01b0319831681178455604051919092169283917f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e09190a35050565b5f602082840312156101ee575f5ffd5b81356001600160a01b0381168114610204575f5ffd5b939250505056fea26469706673582212209c50dfa5e6d3c0ad4e4cd316251063600f93c03f2be60be1195306f14b76ea2c64736f6c634300081b0033";

type NihiliumRecoveryRegisterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NihiliumRecoveryRegisterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NihiliumRecoveryRegister__factory extends ContractFactory {
  constructor(...args: NihiliumRecoveryRegisterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _owner: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_owner, overrides || {});
  }
  override deploy(
    _owner: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_owner, overrides || {}) as Promise<
      NihiliumRecoveryRegister & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): NihiliumRecoveryRegister__factory {
    return super.connect(runner) as NihiliumRecoveryRegister__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NihiliumRecoveryRegisterInterface {
    return new Interface(_abi) as NihiliumRecoveryRegisterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): NihiliumRecoveryRegister {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as NihiliumRecoveryRegister;
  }
}
