/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  TestVerifyAlwaysTrue,
  TestVerifyAlwaysTrueInterface,
} from "../../contracts/TestVerifyAlwaysTrue";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_proof",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "_publicInputs",
        type: "bytes32[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506101658061001f6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063ea50d0e414610030575b600080fd5b61004861003e36600461005c565b6001949350505050565b604051901515815260200160405180910390f35b6000806000806040858703121561007257600080fd5b843567ffffffffffffffff81111561008957600080fd5b8501601f8101871361009a57600080fd5b803567ffffffffffffffff8111156100b157600080fd5b8760208284010111156100c357600080fd5b60209182019550935085013567ffffffffffffffff8111156100e457600080fd5b8501601f810187136100f557600080fd5b803567ffffffffffffffff81111561010c57600080fd5b8760208260051b840101111561012157600080fd5b94979396506020019450505056fea2646970667358221220ab9328c10ada7d561fc9042d33e16b0235c8543fcb132f6d222f812b7f9ef47364736f6c634300081b0033";

type TestVerifyAlwaysTrueConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TestVerifyAlwaysTrueConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TestVerifyAlwaysTrue__factory extends ContractFactory {
  constructor(...args: TestVerifyAlwaysTrueConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TestVerifyAlwaysTrue & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): TestVerifyAlwaysTrue__factory {
    return super.connect(runner) as TestVerifyAlwaysTrue__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestVerifyAlwaysTrueInterface {
    return new Interface(_abi) as TestVerifyAlwaysTrueInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TestVerifyAlwaysTrue {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as TestVerifyAlwaysTrue;
  }
}
